### ISSUE TITLE
[v2.3.2] Bubble Card Buttons Unresponsive

### ISSUE THREAD

**Issue by Youri3246** [Clooos/Bubble-Card#1035]
**Describe the bug**  
After updating to version 2.3.2, the bubble card interface becomes noticeably laggy when a button is pressed. At times, the buttons fail to respond entirely. Reverting to version 2.3.0 resolves the issue

**Informations (please complete the following information):**  
 - OS: [iOS 18.2]
 - Browser/App: Home Assistant App 2024.12.1 
 - Bubble Card version: v2.3.2
 - Home Assistant version: 2024.12.2

**Additional context**  
Reverting to version 2.3.0 resolves the issue

https://github.com/user-attachments/assets/a8246288-4f3f-4eca-9deb-26fc923221f5

](url)

Thank you! 🍻

**Comment by obsthaendler91** [comment]
i have the same issue

**Comment by thomasvh6** [comment]
I also got this issue, it takes around 7 seconds to open, it loads part of the popup and after an additional 7 seconds, it loads the icons. A rollback to 2.3.0 solves the issue.
OS: Android & Windows
HA Core: 2024.12.2

**Comment by Clooos** [comment]
Hi! I've released a new version, even if I'm not sure that it could resolve this issue, to be honest I have no idea of what is slowing down everything, I don't have this issue on my setup.

Can someone take a look at his browser console? There might be some Bubble Card errors.

**Comment by Youri3246** [comment]
I've checked, and unfortunately, the issue still persists.
I checked the browser console, and here’s what I see:

https://github.com/user-attachments/assets/00a353c3-2900-42af-ab33-e0c1bc465a80

**Comment by Clooos** [comment]
Perfect! Thank you!

**Comment by Clooos** [comment]
I might have fixed this. 

Could you try this version? You need to remove Bubble Card from HACS first, then install it with the "[Without HACS](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#installation)" method.

[bubble-card.js.zip](https://github.com/user-attachments/files/18126106/bubble-card.js.zip)

Once installed, clear your cache then check in the editor if you see v2.3.4.

Thank you in advance! 🤞

**Comment by Youri3246** [comment]
I've tested it, is see version 2.3.4. and all the errors above are resolved. However, after using it a few times, the dashboard tends to slow down again. The buttons are responding more slowly than before, and the performance isn't as snappy as it was prior to the update. I also cleared the cache, but this didn't make any difference.


https://github.com/user-attachments/assets/66ed9807-9fa4-483d-9ecc-0f100a830814

**Comment by Clooos** [comment]
@Youri3246 was it working smoothly on v2.3.0?

**Comment by Youri3246** [comment]
@Clooos Yes

**Comment by Clooos** [comment]
I will check that again, thank you for the feedback!

**Comment by MrBearPresident** [comment]
@Youri3246 
Do you have any kind of pop-up triggers, or conditional sub-buttons configured?

**Comment by MrBearPresident** [comment]
Could you try this one?
**NOTE**: Automatic pop-up triggers and conditional sub-buttons won't work
[bubble-card.js.zip](https://github.com/user-attachments/files/18127029/bubble-card.js.zip)

**Comment by Youri3246** [comment]
Much better! The buttons seem to be working as they should now. Faster would be even better, haha. It seems to be resolved.


https://github.com/user-attachments/assets/bc93891a-d8c5-46fd-ad6c-2ee70b73daf5

**Comment by MrBearPresident** [comment]
😓, that means that the validation of the conditionals is causing all this....
I copied a lot of the [default HA-code](https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/common/validate-condition.ts) and removed all types, because bubble-card is without types. 

For some reason theirs doesn't cause problems and mine does....

**Comment by Youri3246** [comment]
After a couple of hours it is again slow and laggy.

**Comment by MrBearPresident** [comment]
> After a couple of hours it is again slow and laggy.

@Youri3246 thanks for your patience and your willingness to be our guinea pig. The fact that Cloos and I never saw this frustrates me a little bit. The only thing I can think of is that our devices are to fast? So that javascript fires aren't stacking up?? 

I want to try something to further distil what the problem is. 
I will send you a new build in a couple of minutes.

**Comment by MrBearPresident** [comment]
New version to try:
Most of the code is from 2.3.3 except the conditions for pop-ups
[bubble-card.js.zip](https://github.com/user-attachments/files/18131574/bubble-card.js.zip)

**Comment by Youri3246** [comment]
I tested it. On mobile it seems fine, but in the browser it does **not** work smoothly. I also have errors in the browser console.

https://github.com/user-attachments/assets/ffa7c5b6-1be2-483f-a940-dab03dc95bed

**Comment by giuseppebaldi** [comment]
Having the same issue here, super laggy and unresponsive. Couples of things I've noticed: the pop-ups are super laggy, I can't close them once their open either from the X or clicking outside the pop-up. Any commands (turn lights off, etc.) either never happen or happen with a VERY long delay. 

The pop-up header is blank (see attached)
![Screenshot_20241214-191348](https://github.com/user-attachments/assets/d026160d-3ff6-431c-a716-cf01594b816a)


 and in edit mode the pop-up cards don't exist, there should be several between the remote cards (see attached).

![Screenshot_20241214-191540](https://github.com/user-attachments/assets/2a97d072-79f6-4f1d-b46f-16b1e1addf5d)

**Comment by giuseppebaldi** [comment]
I was able to fix my issue completely. All my headers were set to state with no entity defined, I changed to Name/Text and ask good now.

**Comment by Clooos** [comment]
Nice! I'm working on a new release, we will see if things works best after that 🙏

**Comment by Youri3246** [comment]
Again laggy on mobile.. Seems that is is slow after some time.

**Comment by ki5ck** [comment]
Just started using this for my wall tablet, and I've noticed it's getting very laggy as well. Force closing WallPanel and the browser fixes it for a bit, but then it gets laggy again after a while.

**Comment by MrBearPresident** [comment]
@ki5ck
A solution is to roll back to 2.3.0
We (@Clooos and myself) are not 100% sure why this is caused.
We are working on it.

**Comment by ki5ck** [comment]
I rolled back to 2.3.0, and after sitting overnight, it was completely unresponsive (after 15 seconds with no activity, I force quit). Restarting the browser fixed it.

**Comment by Clooos** [comment]
Hi! I might have correctly fixed the slowness/performance issues over time, can someone try this version?

As usual, to install it you need to remove Bubble Card from HACS first, then install it with the "[Without HACS](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#installation)" method.

Once installed, clear your cache then check in the editor if you see v2.3.4.

Thank you in advance! 🤞

[bubble-card.js.zip](https://github.com/user-attachments/files/18195219/bubble-card.js.zip)

**Comment by Youri3246** [comment]
I did not solved the problem. I wiped the cache en rebooted.
I checked: version 2.3.4

https://github.com/user-attachments/assets/defe3006-68a0-4cb8-8bb3-05caef88b51d

**Comment by Youri3246** [comment]
> Can you send me the YAML of this view? This will maybe help me reproduce this.

https://pastebin.com/La6ZPj3u

**Comment by Youri3246** [comment]
It looks now after a couple of hours that it is working as before the problem.

**Comment by Clooos** [comment]
So would you say that this is fixed? It was maybe a cache issue 🤞

**Comment by Youri3246** [comment]
> So would you say this is fixed? It was maybe a cache issue 🤞
> 
> Edit: On some iOS devices it's sometimes better to reboot it to fully clear the cache/memory. Are you on iOS?

I checked again, and for some reason, I was sleeping yesterday evening and reverted to version 2.3.0. wich works good.
The issue still exists in version 2.3.4 Sorry!

**Comment by Clooos** [comment]
Ok, false hope! 😅

I will try again by testing your YAML.

**Comment by ChrisChapman** [comment]
I've just checked 2.3.3 again.

For me, as soon as I go to my dashboard the browser becomes unresponsive and the following error are in console

![image](https://github.com/user-attachments/assets/48d8d885-9c02-4da3-89ac-3c029b590211)

**Comment by Clooos** [comment]
@ChrisChapman have you tried [this version](https://github.com/Clooos/Bubble-Card/issues/1035#issuecomment-2553149807)?

Do you also have this error in it?

**Comment by Clooos** [comment]
@Youri3246 here's another version, could you try it? 

[bubble-card.js.zip](https://github.com/user-attachments/files/18209077/bubble-card.js.zip)

@ChrisChapman you can try this one instead.

**Comment by ChrisChapman** [comment]
> @Youri3246 here's another version, could you try it?
> 
> [bubble-card.js.zip](https://github.com/user-attachments/files/18209077/bubble-card.js.zip)
> 
> @ChrisChapman you can try this one instead.

@Clooos Yes this seems to have resolve it for me - no crashing or console errors!

**Comment by Clooos** [comment]
I will wait for @Youri3246's answer, then if it's all good, I will release this version 🙂

**Comment by Youri3246** [comment]
> I will wait for @Youri3246's answer, then if it's all good, I will release this version 🙂

No more errors, and my dashboard is now fully responsive! 🥇
Everything is working perfectly. I can say it's all been solved now!

Thank you so much for being so responsive and helpful!

**Comment by Clooos** [comment]
I've been waiting for this comment all day! 🎉

I will do my best to release this version really soon!

**Comment by Clooos** [comment]
Hi! The new release is here, everything should be stable now! 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.4-beta.1
