### ISSUE TITLE
[2.3.3] Climate Card Issue

### ISSUE THREAD

**Issue by Th-Ar** [Clooos/Bubble-Card#1058]
There's a problem with climate maps concerning presets in sub-buttons. These do not update when they change.

Illustration : 

https://github.com/user-attachments/assets/f17704ec-8104-4b86-93eb-e3f884633294

**Comment by Clooos** [comment]
Hi! I will take a look at this 👌

**Comment by Clooos** [comment]
Hi again! This issue should be fixed in the next release 🙂

**Comment by Th-Ar** [comment]
Hello,
For information, I tried with the beta (2.3.4 beta 1), the problem is still present.
Bye

**Comment by Clooos** [comment]
Hi! Indeed I had to focus on the major issues introduced in the previous releases, but I will do my best to fix it soon 🙂

**Comment by Th-Ar** [comment]
Hello,
Thanks for the new version 2.3.4., but the bug still present in this version. Normal ? (I'm not very familiar with how Github works ;) )

**Comment by Clooos** [comment]
Hi! This should be fixed, I've just tried again and this is working on my side. Have you cleared your browser/app cache? Sometime the old version stay in the cache.

**Comment by Clooos** [comment]
Well... I will try to reproduce this again 😅

**Comment by vrcdx64** [comment]
Hi! Exactly same problem here. Don't hesitate if you want more informations or tests or my side!

**Comment by Th-Ar** [comment]
Hello,
Same behavoir with the last update 😢
