### ISSUE TITLE
(v2.3.0) - Delay in FullyKioskBrowser

### ISSUE THREAD

**Issue by Schwippser** [Clooos/Bubble-Card#1065]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
BubbleCard v.2.3.0 is responsible for delays of up to 20seconds in FullyKioskBrowser

**To Reproduce**  
1. Update to BubbleCard v2.3.0
2. refresh
3. lokk at a ClockCard at FullyKiosk
4. you will see the delay

HA OS 14.1
HA Core v2024.12.4
HA Supervisor v2024.12.0

i have to go back to v2.2.4

**Comment by Clooos** [comment]
Hi! Could try this version? I optimized a lot of code and everything should be smoother with it.

https://github.com/Clooos/Bubble-Card/issues/1035#issuecomment-2556665446

The instructions to install it are a few comments above.

🤞

**Comment by Clooos** [comment]
Hi! The new release is here, this should fix this issue! 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.4-beta.1

**Comment by MrBearPresident** [comment]
Please confirm if the problems are solved.

**Comment by ki5ck** [comment]
I am using version 2.3.4beta1 with Fully Kiosk and the problem is still there. A browser refresh fixes the problem for a time.

**Comment by Clooos** [comment]
And this was not an issue in v2.2.4?

**Comment by ki5ck** [comment]
I’m a new user.  The first version I installed was 2.3.0.

**Comment by Clooos** [comment]
Oh ok, could you check your browser console to see if there are some errors? Check this on your computer's browser, and if you don't know how check on Google.

There is maybe an other issue that is not related to Fully Kiosk Browser, I use it as well and it's really smooth all the time.

**Comment by ki5ck** [comment]
I had not cleared the cache. I just set it to clear after every auto refresh and I will monitor to see how it does.

**Comment by Clooos** [comment]
Any news on this? 🙂

**Comment by ki5ck** [comment]
I am still getting slow response after it’s been open for a while. I’ve just been refreshing the page before I try to use the bubble controls. Haven’t checked the browser console yet because I’m not eager to pull my tablet off the wall, and everything I’ve read about it requires a usb direct connection between tablet and pc.

**Comment by Clooos** [comment]
I was talking about your desktop's browser console, no need to check on your tablet directly.

**Comment by Clooos** [comment]
None of these errors seems related to Bubble Card, have you tried without Bubble Card? Is the slowness coming after some time as well?

**Comment by ki5ck** [comment]
No, everything else seems to work ok. It's just when I tap the button to open the popup menu, it takes 3 or 4 seconds to appear. Refreshing the page and tapping makes the popup appear instantly.

**Comment by Clooos** [comment]
Good to know, I guess that there is still something that can be optimized with the pop-ups. I just don't know when I will be able to try that.

**Comment by emms007** [comment]
Hello @ki5ck  I am having the same issue with the FullyKioskBrowser;
Looking at the Android settings (Chinese cheap tablet), I noticed there is a "performance mode". Activating this helped to keep a constant speed. I think the tablet goes to energy saving, despite running 24/24, and is not so reactive to jump-up its performances upon the first interactions. Performance mode helped.

**Comment by Clooos** [comment]
Hi! I've made a lot of progresses on performance in v2.5.0-beta, can you try it? Don't forget to clear your FullyKiosk app cache.

**Comment by aaronegger** [comment]
Hi, i also have the same issues. 
But i noticed that this could also occur when using the same dashboard on my pc.
First it works fine, but after a while it becomes completely unresponsive.
I left the window unattended for maybe a few minutes and the also pressing buttons had no effect, despite the pressing animation.

So it seems not hardware related but a bug.
I am using the version 2.5-beta5.

**Comment by aaronegger** [comment]
I stumbled on another issue that states that cardmod could be the issue. I remove that addon and observe it this is the solution.
Luckly i am not depending on that mod, so that would be a nice fix^^

**Comment by Clooos** [comment]
This is good to know!

I still use it on my config for a few other custom cards, I should try without it 😁

I'm closing this then, thank you for the feedback!
