### ISSUE TITLE
Buggy and slow

### ISSUE THREAD

**Issue by mash2k3** [Clooos/Bubble-Card#130]
I just created 2 cards popup and horizontal stack and it suddenly lock up on editing page. i have to exit out of HA tab and re-open then the edit button for HA disappear. i have to uninstall bubble component to get the edit buttons back then delete the cards. I tried a few times but no success. I really love the concept and look. Ill wait for more stable version.

**Comment by korsmann** [comment]
Same issue.  Got it working but experienced same issue.  Reboot of the Proxmox VE to get my HA instance working again.
Retried and it appeared to work fine, but after 12hrs it lock down HA preventing me from accessing my environmentm needing to restart the VE again....like the pop-up but have to remove them overall....

**Comment by Nuuki9** [comment]
I got part way through configuring a card but then HA froze and eventually gave me an "out of memory" error. I tried a few times and it happened each time. 

I'll jump in once there's a new version out as it looks very cool.

**Comment by Clooos** [comment]
Hi and thanks for your feedback, this issue is fixed in v1.4.0 and up!

**Comment by Nuuki9** [comment]
This isn't resolved for me. I just updated to v1.4.2 and after a few tests to nail dowen the bahaviour, here's what I'm seeing:

1. Create a new dashboard tab.
2. Add a Bubble pop-up card - add a hash value and nothing else. Save.
3. Browse to that dashboard tab.
4. Now, browse to _any other_ dashboard tab.

At that point the browser freezes, and eventually crashes with an "out of memory" warning. Looking at Task Manager, I see my memory usage for the my browser start to rise quickly at step 4, until it crashes.

I've repeated this a bunch of times, using Brave and Edge, and its happening every time.

**Comment by Nuuki9** [comment]
I've created a new Issue for what I'm seeing, as this one is Closed and may be different.
