### ISSUE TITLE
[2.5.0-beta.8] button type card no longer have vibration feedback on mobile devices

### ISSUE THREAD

**Issue by xiayesuifeng** [Clooos/Bubble-Card#1354]
**Describe the bug**  
button type card no longer have vibration feedback on mobile devices

**YAML**  
If applicable, add any relevant YAML code.

```
type: custom:bubble-card
card_type: button
modules:
  - default
entity: light
button_type: name
name: test
```

**Informations (please complete the following information):**  
 - OS: Android
 - Browser/App: App
 - Bubble Card version: 2.5.0-beta.8
 - Home Assistant version: 2025.3.1

Thank you! 🍻

**Comment by CZonin** [comment]
@Clooos Still seems to be happening on beta.9. For me, it's happening on all of the cards on my second page.

I have 2 pages in my setup. My default page has haptic feedback on everything and is working as expected. On the second page none of my cards have haptic feedback.

**Comment by Clooos** [comment]
What?? 🙃

Are you sure that you got the right version (there is currently an HACS issue causing some issues when downloading the new releases, sometimes it even get a previous one), because I just tried on mine and everything is working correctly, even on my other pages.

**Comment by xiayesuifeng** [comment]
After updating to beta.9, the problem still exists. As shown in the picture, the upper part has vibration feedback, but the lower part does not.

![Image](https://github.com/user-attachments/assets/d32c4611-845c-4a79-a5e0-1f0d4bb0e935)

**Comment by CZonin** [comment]
> What?? 🙃
> 
> Are you sure that you got the right version (there is currently an HACS issue causing some issues when downloading the new releases, sometimes it even get a previous one), because I just tried on mine and everything is working correctly, even on my other pages.

Ya definitely on the latest beta. Just redownload through HACS to be sure and still have the issue.

**Comment by Clooos** [comment]
Have you checked the version at the bottom of the editor? That's the only way to be sure of that.

**Comment by CZonin** [comment]
> Have you checked the version at the bottom of the editor? That's the only way to be sure of that.

![Image](https://github.com/user-attachments/assets/2ffb3afc-d265-4c3a-8c19-039510f36aa3)

**Comment by Clooos** [comment]
Damn! 🫠

I really don't understand what's happening then. For your lower part, I see that you're using a module? Is it happening without it?

**Comment by Clooos** [comment]
Can you tell me if you see any error in the browser console when you press one of that button? And also is the YAML identical across these cards?

**Comment by xiayesuifeng** [comment]
It seems that when the button type is Name / Text, there will be no vibration feedback and click animation. When it is State, there will be.

There are no errors in the console.

```
type: custom:bubble-card
card_type: button
modules:
  - default
entity: light
button_type: name
name: test
button_action:
  tap_action:
    action: navigate
    navigation_path: "#test"
```
> No vibration feedback and click animation


```
type: custom:bubble-card
card_type: button
modules:
  - default
entity: sensor.24e8ce19de63_freezertemperaturec
button_type: state
name: test
sub_button:
  - entity: light.smart_switch_f3_back_bedroom_2_light_strip
    name: ""
  - entity: light.smart_switch_f3_back_bedroom_2_desk_spotlight
button_action:
  tap_action:
    action: navigate
    navigation_path: "#test3"
```
> Has vibration feedback and click animation

**Comment by Clooos** [comment]
Thank you! This must be the reason, I will check that and this should be fixed for the next (and hopefully last) beta.

**Comment by CZonin** [comment]
I think @xiayesuifeng is correct. The first card below has haptic feedback, the second doesn't.

```
type: custom:bubble-card
card_type: button
entity: light.living_room_light
card_layout: large
button_type: switch
columns: 2
name: Living Room
icon: mdi:sofa
sub_button:
  - entity: media_player.living_room_shield
    show_background: false
    icon: mdi:television
    tap_action:
      action: navigate
      navigation_path: "#living-room"
    hold_action:
      action: call-service
      service: light.toggle
      target:
        entity_id: light.living_room_light
  - entity: sensor.living_room_thermostat_temperature
    show_state: true
    show_name: false
    show_icon: false
    show_background: false
    tap_action:
      action: navigate
      navigation_path: "#living-room"
    hold_action:
      action: call-service
      service: light.toggle
      target:
        entity_id: light.living_room_light
tap_action:
  action: navigate
  navigation_path: "#living-room"
double_tap_action:
  action: none
hold_action:
  action: toggle
button_action:
  tap_action:
    action: navigate
    navigation_path: "#living-room"
  double_tap_action:
    action: none
  hold_action:
    action: toggle
styles: >2
    .bubble-sub-button-1 {
      display: ${hass.states['media_player.living_room_shield'].state === 'on' ? '' : 'none'} !important;
      opacity: 50%;
    }
    .bubble-sub-button-container {
      gap: 0px !important;
    }
  ${card.querySelector('.bubble-sub-button-2').innerText =
  Math.round(hass.states['sensor.living_room_thermostat_temperature'].state) +
  "°"}
scrolling_effect: false
modules:
  - default
  - round_icon_container
```

```
type: custom:bubble-card
card_type: button
button_type: name
card_layout: large
columns: 2
icon: phu:unraid
name: Unraid
tap_action:
  action: navigate
  navigation_path: "#unraid"
button_action:
  tap_action:
    action: navigate
    navigation_path: "#unraid"
sub_button:
  - entity: sensor.cpu_temperature
    show_state: true
    show_background: false
    show_icon: false
    tap_action:
      action: navigate
      navigation_path: "#unraid"
styles: >
  ${card.querySelector('.bubble-sub-button-1').innerText =
  Math.round(hass.states['sensor.cpu_temperature'].state) + " °C"}
scrolling_effect: false
modules:
  - default
  - round_icon_container
```

**Comment by ossebol** [comment]
> Thank you! This must be the reason, I will check that and this should be fixed for the next (and hopefully last) beta.

[Bubble Card v2.5.0-beta.9] did not fix this. In my case also with the name/text button type. Issue #1372 confirms this

**Comment by Clooos** [comment]
Hi everyone, I just fixed this. This fix will be part of the next beta 🙂

**Comment by CZonin** [comment]
> Hi everyone, I just fixed this. This fix will be part of the next beta 🙂

Looking forward to it @Clooos !
