### ISSUE TITLE
Sliders behaving as simple buttons - only able to toggle / no adjustment

### ISSUE THREAD

**Issue by promufa** [Clooos/Bubble-Card#1373]
**Describe the bug**  
I know a lot has changed in the sliders in the last few releases so I might have missed some breaking change but sliders are no longer working for me. They behave as simple buttons. Confirmed on both Android app and PC / web page. Currently on 2.5.0 beta 9. My dashboard is the old style (eg not sections) which may play a role here. Opening the "more info" (clicking on the icon on the left of the slider) opens the more info pop-up as expected and the slider there works as expected.

**To Reproduce**  
1. Create or have an old-style dashboard
2. Create a pop-up vertical stack, add light sliders, save
3. Open pop-up and try to adjust slider --> nothing happens.

**Expected behavior**  
Slider should allow adjusting light levels by hold and drag.

**Screenshots**  

**YAML**  
Adding yaml config of just one pop-up as an example
```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#Living"
    name: Lounge
    icon: mdi:sofa
    entity: light.living_room_sconce
    bg_color: "#504151"
    width_desktop: 640px
    modules:
      - default
  - type: custom:bubble-card
    card_type: separator
    name: Lights
    icon: mdi:lightbulb-on-outline
  - type: custom:bubble-card
    card_type: button
    entity: light.living_room_sconce
    button_type: slider
    show_state: true
    name: Sconce
    button_action:
      hold_action:
        action: toggle
    slider_live_update: true
    modules:
      - default
  - type: custom:bubble-card
    card_type: button
    show_state: true
    entity: light.wooden_lamps_group
    name: Side lamps
    button_type: slider
    button_action:
      hold_action:
        action: toggle
    slider_live_update: true
  - type: custom:bubble-card
    card_type: separator
    name: Blinds
    icon: mdi:blinds-horizontal-closed
    sub_button:
      - name: Shade
        icon: mdi:blinds-horizontal
        show_name: true
        tap_action:
          action: call-service
          service: script.turn_on
          target:
            entity_id: script.shade_living_room_2
        show_background: true
  - type: custom:bubble-card
    card_type: cover
    entity: cover.large_blinds
    force_icon: true
    show_name: true
    show_icon: true
    name: Left blinds
    icon_down: mdi:archive-arrow-down
    icon_up: mdi:archive-arrow-up
    icon_open: mdi:window-shutter-open
    icon_close: mdi:window-shutter-settings
    show_state: true
    show_last_updated: true
    show_attribute: true
    attribute: current_position
  - type: custom:bubble-card
    card_type: cover
    entity: cover.small_blinds
    force_icon: true
    show_name: true
    show_icon: true
    name: Right blinds
    icon_down: mdi:archive-arrow-down
    icon_up: mdi:archive-arrow-up
    icon_open: mdi:window-shutter-open
    icon_close: mdi:window-shutter-settings
    show_state: true
    show_last_updated: true
    show_attribute: true
    attribute: current_position
  - type: custom:bubble-card
    card_type: separator
    name: Audio / Video
    icon: mdi:monitor-speaker
  - type: custom:bubble-card
    card_type: button
    entity: switch.projector_plug
    name: Projector
    icon: mdi:projector
    show_state: true
  - type: custom:bubble-card
    card_type: button
    entity: media_player.yamaha_av_rx_v579
    button_type: slider
    show_state: true
    slider_live_update: true
    show_attribute: false
    attribute: supported_features
    force_icon: false
    show_icon: true
  - type: custom:bubble-card
    card_type: button
    entity: switch.wake_on_lan_2
    name: Media centre
    icon: mdi:laptop
    show_state: true
    show_last_changed: false
    show_attribute: false
    attribute: friendly_name
  - type: custom:bubble-card
    card_type: separator
    name: Climate
    icon: mdi:home-thermometer-outline
  - square: false
    type: grid
    cards:
      - type: entity
        entity: sensor.humidity_living_temperature
        name: Temperature
        theme: Bubble
        state_color: true
      - type: entity
        entity: sensor.humidity_living_humidity
        name: Humidity
        state_color: true
        theme: Bubble
    columns: 2
```

**Informations (please complete the following information):**  
 - OS: HAOS / android app / win10
 - Browser/App: HA app / Chrome
 - Bubble Card version: 2.5.0 beta 9
 - Home Assistant version: 2025.3.4

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
Yes indeed! I realized that a few days after the release, but I just fixed it. 

This fix will be part of the next beta 🙂

**Comment by promufa** [comment]
Thank you very much! Looking forward to the next release

**Comment by promufa** [comment]
This seems to persist in v3.0.0 beta2

**Comment by Clooos** [comment]
I just released a new beta to fix some issues, but this one will be next!

Thank you for the feedback!

**Comment by Clooos** [comment]
Just to be sure, have you try to hold it to slide with it? The new behavior is a bit different than the previous one, and can be reverted in the editor if needed, in the Slider settings.

**Comment by promufa** [comment]
Thanks for looking into this. Whether I hold on some position on the slider bar or slide over directly the effect is these same unfortunately, just toggle.

**Comment by Clooos** [comment]
Hi! I forgot to mention it, but this issue should be fully fixed now, can you confirm this? 🙂

**Comment by promufa** [comment]
Hi!, Nope, still an issue for me. I have reverted to the old style and that work OK. It looks like other people are not seeing this though. Is there something off with my setup maybe ?

**Comment by Clooos** [comment]
Are you sure the update was done correctly? Sometime HACS doesn't clear the cache correctly. The best way to be sure is to check the version at the bottom of the Bubble Card editor.

Also, like I said before, you need to hold then slide, but I guess you already tried that.

I really want to reproduce this issue, but still unsure how.

**Comment by promufa** [comment]
Hey! I can confirm the version is 3.0.0-beta.5.
Adding a short clip showing the behaviour I see on a desktop PC.
https://github.com/user-attachments/assets/3f9d868c-db4c-4205-ad83-414262d5d1db

**Comment by Clooos** [comment]
Are you holding instead of just clicking on that video?

**Comment by promufa** [comment]
Yes, if you turn on sound you can can kinda hear the mouse clicks. Difficult to capture that in screen recording ;)

**Comment by Clooos** [comment]
Damn this is weird. I really have no clue, everything is working on my side and no one else have reported a similar issue 😅

Can you try with a slider outside of a pop-up? And can you also try again on Android? Without a way to reproduce this, I will not be able to fix this.

**Comment by promufa** [comment]
Hi @Clooos - again thank you very much for looking into this. I think we are getting somewhere now.

I created a slider outside a pop-up and it works as intended. I have also created a new pop-up and added a slider inside there and that also works. The unexpected behaviour is only seen with sliders that were pre-dating the slider updates. I am not sure if that affects only sliders inside pop-ups or all sliders (mine were all inside pop-ups) or if that was listed as a breaking change already for that matter.

Creating a new slider inside the existing pop-ups seems to resolve the issue, so - while a bit tedious - there is a solution here by re-creating all the sliders I am using.

**Comment by Clooos** [comment]
Hi! I have found why your new sliders are working as expected and why the previous ones were just toggling the entity.

Check your YAML:

```yaml
- type: custom:bubble-card
    card_type: button
    entity: light.living_room_sconce
    button_type: slider
    show_state: true
    name: Sconce
    button_action:
      hold_action: <-----
        action: toggle <-----
```

Button's hold action is disabled in the editor for sliders, but it can indeed be added in YAML, I guess it was previously a switch then you've changed it to a slider.

Anyway, I should have better checked your YAML.

I'm glad this was not an issue from my code! 😄

**Comment by promufa** [comment]
I was expecting this to be something dumb on my side :)
Thanks for the help and all the hard work that has gone into this awesome UI
