### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by liamstears** [Clooos/Bubble-Card#1386]
**Describe the bug**  
Although the card seems to be working as expected I am seeing errors in the dev console

http://*IP REDACTED*/local/bubble/bubble-modules.yaml?v=1743841699170 net::ERR_ABORTED 404 (Not Found)

'bubble-modules.yaml' not found at /local/bubble/bubble-modules.yaml?v=1743841699170 (status: 404). Trying next...

Some sort of error not being able to find bubble-modules.yaml

**To Reproduce**  
Hit F12 on browser and check console

**Expected behavior**  
No dev console errors

**Informations (please complete the following information):**  
 - Browser/App: Brave
 - Bubble Card version: 2.5.0-beta.9
 - Home Assistant version: 2025.4.1

Thank you! 🍻

**Comment by liamstears** [comment]
> Hi! This error can be ignored if you don't want/need to use modules, check the Module section in the editor, the steps to configure modules are explained in it.

Thank you, trying to clear out all my errors so just copied over the yaml to stop the error, thank you 👍🏻

**Comment by Clooos** [comment]
You're welcome! 

By the way, I've removed that message, it should not appears anymore even if the file isn't copied 🙂

**Comment by de666** [comment]
> By the way, I've removed that message, it should not appears anymore even if the file isn't copied 🙂

@Clooos unfortunately it seems it keeps trying to download that file, searching for:
```
/local/bubble/bubble-modules.yaml
/hacsfiles/Bubble-Card/bubble-modules.yaml
/local/community/Bubble-Card/bubble-modules.yaml
```
I tried to put an empty file bubble-modules.yaml inside the www/Bubble-Card folder and it works (no more 404 error) but only for one of the three GET request (obviously), so some 404 errors are still present.
I have a reverse proxy with fail2ban filter for 404 errors which bans the ip if there are 3 errors of that type. For now I put a specific ignore rule but it would be nicer to solve this issue without a workaround on fail2ban.
Is it possible to prevent bubble-card asking for non mandatory configuration files?
Thankyou very much for the huge work!!

**Comment by AlkaDragos** [comment]
Hello, i have the same issue. Got to this post by searching for an answer, created an empty **bubble-modules.yaml** file in the **www/community/Bubble-Card/** as suggested here and some 404 errors disappeared. Still got one `:8123/local/bubble/bubble-modules.yaml?v=1752389928550:1  Failed to load resource: the server responded with a status of 404 (Not Found)` and can't find the reason why. I'm on the latest stable version 3.0.0, cleared the cache and forced refresh. 

Thank you very much for your this @Clooos and keep up the good work! 👍

**Comment by Clooos** [comment]
Hi! I'm reopening this issue, and I will see what I can do 👍

I will be in vacation, so I will not be able to work on this until I'm back 🙂

**Comment by AlkaDragos** [comment]
> Hi! I'm reopening this issue, and I will see what I can do 👍
> 
> I will be in vacation, so I will not be able to work on this until I'm back 🙂

Thank you very much for your fast response.😊 Ofc, i just wanted to let you know that it's still there.

Have a great vacation and a beautiful weather 👍

**Comment by Normanras** [comment]
Found this issue because I see the same issue! I don't know if it's related, but I'm using a module from the store and I have applied it to 4 of my cards but the module in question only shows up on 2 cards. The error then appears twice in the console. Not saying it's related, just saying I found I very loose connection between what I'm seeing on my dashboard and the errors. Thanks again for all your hard work on this!

**Comment by liamstears** [comment]
Clearing out errors in dev console again, cleaning up code, noticed this is still present, any solution yet?

**Comment by Clooos** [comment]
Hi! Just add an empty `bubble-modules.yaml` in the `/www/bubble` folder (you will have to create it), there is nothing else that can be done on my side (without removing the ability to manage modules in YAML).

**Comment by Clooos** [comment]
Hi! Just wanted to say this will finally be fixed in v3.1.0, this version will use a better system 👌

**Comment by hausmanconsulting** [comment]
I've upgraded to 3.1.0 and I'm still getting this in the console:

`http://[ha-ip]/local/bubble/bubble-modules.yaml?v=1769377659473
[HTTP/1.1 404 Not Found 2ms]`

I'm probably doing something wrong, but just wanted to mention it since I'm chasing down some issues today.

**Comment by Pel1can111** [comment]
same here, running the latest version but seeing "https://XXX.XXX.XXX.XXX:XXXX/local/bubble/bubble-modules.yaml?v=1770304828538" in the console.

**Comment by Clooos** [comment]
Hi! You have to install Bubble Card Tools to remove this error, this is the only way and one of the many reasons that pushed me to work on this integration 🙂

https://github.com/Clooos/Bubble-Card-Tools

**Comment by GiuseppeP96** [comment]
Still having this error:
local/bubble/bubble-modules.yaml?v=1788416036818
Request Method
GET
Status Code
404 Not Found
bubble-card.js?hacstag=680112919330:373
 Bubble Card - The legacy modules file '/local/bubble/bubble-modules.yaml' was not found (404). This check happens when Bubble Card Tools is not installed or not available. Install Bubble Card Tools to manage modules and stop seeing this 404 in the console: https://github.com/Clooos/Bubble-Card-Tools 
But i have installed both the bubble card and the tools

<img width="1010" height="204" alt="Image" src="https://github.com/user-attachments/assets/5624d3d7-e21f-49bb-9d20-ed518d0627f7" />

Also i'm experiencing auto browser refresh loop with latest HA version with bubble card installed
