### ISSUE TITLE
Card Type selection broken with 3.0 beta1

### ISSUE THREAD

**Issue by erazorlll** [Clooos/Bubble-Card#1416]
**Describe the bug**  
Adding a new bubble card to the dashboard and then selecting the card type doesn't work. 
As soon as I use the drop-down nothing happens. Doesn't matter which card type I choose. 
 
I had previously v2.5.0-beta.9 installed and worked without problems. 
I used the redownload function of HACS and downloaded the new v3.0.0-beta.1. 

I also tried to empty the complete cache of the browser (Chrome), without any luck.
Tried Edge browser but also doesn't work with Edge. 

**To Reproduce**  
1. Starting editing the dashboard
2. Add new card and select "Bubble card"
3. Pop-Up with selection of card type and information about Beta and donation opens
4. Use drop-down and select any card type (e.g. climate, switch, etc.)
5. Nothing changes / happens

**Expected behavior**  
Configuration of card is shown. 

**Screenshots**  
![Image](https://github.com/user-attachments/assets/0175e258-4b25-40a6-82c3-17c7a16bcd0e)

**YAML**  
Not relevant

**Informations (please complete the following information):**  
Core 2025.4.3
Supervisor 2025.04.0
Operating System 15.2 
Frontend 20250411.0
Chrome Version 135.0.7049.115

**Additional context**  
Great work!

Thank you! 🍻

**Comment by thrunkmo** [comment]
Same, thanks for posting!

**Comment by Peethiplatsch** [comment]
I can confirm this issue on my end. But the existing ones remain functional :)

**Comment by pgale** [comment]
When I download beta 1, all my bubble card elements stop working as HA can't find bubble-card at all.
@Peethiplatsch - are you sure your browser isn't caching the old version maybe? It's totally broken for me - can't add a new bubble card (doesn't exist in the list) and old elements not found/broken.

**Comment by oerix** [comment]
Same here, also the editor has become very sluggish. There seems to be a memory leak somewhere, or the new module store is using a lot of resources.

**Comment by Clooos** [comment]
> When I download beta 1, all my bubble card elements stop working as HA can't find bubble-card at all. [@Peethiplatsch](https://github.com/Peethiplatsch) - are you sure your browser isn't caching the old version maybe? It's totally broken for me - can't add a new bubble card (doesn't exist in the list) and old elements not found/broken.

Check this, this is a common issue after some HACS updates.

**Comment by Peethiplatsch** [comment]
@pgale I tried on multiple devices and the existing ones still work. I just can't create new ones because nothing happens after selecting a type. It just continues to say I need to select a card type, just the same behavior as @erazorlll sees

**Comment by Clooos** [comment]
> Same here, also the editor has become very sluggish. There seems to be a memory leak somewhere, or the new module store is using a lot of resources.

For the sluggishness, I just found the cause and this is already fixed on my side.

But I'm unable to reproduce the card type selection issue, so I have no clue, any error in the browser console anyone?

**Comment by Peethiplatsch** [comment]
@Clooos how can I help you that you get more information from my end which could help you? We could have a screen sharing session in Discord or so ^^

**Comment by Clooos** [comment]
If you're using Chrome, check this:

https://developer.chrome.com/docs/devtools/open

Then open the console and you will see the errors in it, a screenshot would be perfect 😃

**Comment by oerix** [comment]
> > Same here, also the editor has become very sluggish. There seems to be a memory leak somewhere, or the new module store is using a lot of resources.
> 
> For the sluggishness, I just found the cause and this is already fixed on my side.
> 
> But I'm unable to reproduce the card type selection issue, so I have no clue, any error in the browser console anyone?

Strangely, I don't have the caching issue anymore for first time lol.
Regarding the sluggishness/selector with the editor, I did notice that it mainly happens when I create a new/edit a popup card.

```card custom:bubble-card Error: You need to define a card type
    setConfig bubble-card.js:2523
    s create-element-base.ts:153
    c create-element-base.ts:179
    c create-element-base.ts:285
    d create-element-base.ts:242
    v create-card-element.ts:108
    value hui-card.ts:123
    value hui-card.ts:42
    value hui-stack-card.ts:75
    _cards hui-stack-card.ts:44
    value hui-stack-card.ts:43
    s create-element-base.ts:153
    c create-element-base.ts:209
    c create-element-base.ts:308
    d create-element-base.ts:242
    v create-card-element.ts:108
    value hui-card.ts:123
    value hui-card.ts:42
    value hui-section.ts:81
    _cards hui-section.ts:337
    value hui-section.ts:336
    value hui-section.ts:209
    value hui-section.ts:109
    performUpdate reactive-element.ts:1328
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    W lit-html.ts:2183
    update lit-element.ts:166
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value hui-dialog-edit-card.ts:294
    handleEvent lit-html.ts:2018
    n fire_event.ts:75
    value hui-element-editor.ts:108
    promise callback*value hui-element-editor.ts:107
    value hui-element-editor.ts:95
    value hui-element-editor.ts:323
    value card-mod.js:1
    i card-mod.js:1
    _handleUIConfigChanged layout-card.js:215
    value hui-element-editor.ts:400
    n fire_event.ts:75
    value hui-stack-card-editor.ts:269
    handleEvent lit-html.ts:2018
    n fire_event.ts:75
    value hui-card-picker.ts:385
    handleEvent lit-html.ts:2018
    _$AI lit-html.ts:2007
    v lit-html.ts:1192
    g lit-html.ts:1553
    _$AI lit-html.ts:1384
    setValue async-directive.ts:366
    update until.ts:94
    promise callback*update until.ts:82
    _$AS directive.ts:134
    $ lit-html.ts:1085
    _$AI lit-html.ts:1362
    v lit-html.ts:1192
    g lit-html.ts:1553
    _$AI lit-html.ts:1384
    T lit-html.ts:1618
    _$AI lit-html.ts:1403
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    W lit-html.ts:2183
    update lit-element.ts:166
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value hui-card-picker.ts:378
[create-element-base.ts:252:12](https://raw.githubusercontent.com/home-assistant/frontend/20250411.0/src/panels/lovelace/create-element/create-element-base.ts)````

**Comment by oerix** [comment]
> These logs aren't helping me, the browser console looks like this:
> 
> <img alt="Image" width="764" src="https://private-user-images.githubusercontent.com/36499953/437014718-38f3a641-eb83-4485-ab80-bb3302a42b52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDU0OTc2NDcsIm5iZiI6MTc0NTQ5NzM0NywicGF0aCI6Ii8zNjQ5OTk1My80MzcwMTQ3MTgtMzhmM2E2NDEtZWI4My00NDg1LWFiODAtYmIzMzAyYTQyYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDI0VDEyMjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NDU4OGRjNTU5NzVlZmIzZjc3YmIwYmJiNjRmNWY4NjhmNDk0YTU2MDQxMDNlMjZkMWY3YmJmNDU4NTE4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SzxHnOvFDjEUZDhUNgp7_-0FahLsItfH7XjIC_3z0AI">

I pasted directly from the console. Anywhere/how I can post without the layout becoming garbled?

**Comment by Clooos** [comment]
Try to find one related to Bubble Card then just send me a screenshot 🙂

**Comment by pgale** [comment]
> > When I download beta 1, all my bubble card elements stop working as HA can't find bubble-card at all. [@Peethiplatsch](https://github.com/Peethiplatsch) - are you sure your browser isn't caching the old version maybe? It's totally broken for me - can't add a new bubble card (doesn't exist in the list) and old elements not found/broken.
> 
> Check [this](https://github.com/Clooos/Bubble-Card/issues/1243), this is a common issue after some HACS updates. [@pgale](https://github.com/pgale) [@oerix](https://github.com/oerix)
> 
> Edit: Forgot the link!!

SOLVED!

Yes, incrementing the /hacsfiles/Bubble-Card/bubble-card.js?hacstag=6801129193001 to /hacsfiles/Bubble-Card/bubble-card.js?hacstag=6801129193002 fixed the problem and I can now see the bubble-card element loading OK :)

**Comment by Peethiplatsch** [comment]
@Clooos here a screenshot from the dev tools console.


![Image](https://github.com/user-attachments/assets/ff95e3f1-1280-46fb-913e-74a279fb1b08)

**Comment by Clooos** [comment]
Could this issue be by any chance fixed in this new beta?

https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-beta.2

**Comment by erazorlll** [comment]
No, still not working. Sorry I forgot to mention, the screen recording above is with beta 2.

**Comment by Clooos** [comment]
I'm on it 🤘

**Comment by blueJack92** [comment]
Hey!

I have the same error, this error code is produced by the browser:

```
Uncaught TypeError: Cannot add property card_type, object is not extensible
    at BubbleCardEditor._valueChanged (bubble-card.js?hacstag=6801129193002:2525:2445)
    at L.handleEvent (bubble-card.js?hacstag=6801129193002:2:129470)
    at n (fire_event.ts:75:8)
    at i.value (ha-combo-box.ts:323:7)
    at U.handleEvent (lit-html.ts:2018:29)
    at x (property-effects.js:328:43)
    at Object.R [as fn] (property-effects.js:353:3)
    at E (property-effects.js:176:12)
    at property-effects.js:263:18
    at it._propertiesChanged (property-effects.js:1925:9)
```

Maybe this will help you ...

**Comment by Peethiplatsch** [comment]
@Clooos also with Beta 2 It’s not working. But I assume your „i am on it“ refers to the fact that youre checking it :)

**Comment by Peethiplatsch** [comment]
I will give it a go and come back to you.

**Comment by Peethiplatsch** [comment]
@Clooos stupid question. In this manual you are saying I need the bubble-card.js file and also a  bubble-pop-up-fix.js file. In your zip is only the bubble-card.js file. Should I download the regular fix file?

**Comment by Peethiplatsch** [comment]
I can't get it working. It's just saying it doesn't exist even after deleting the cache.

I tried the manual you had with the three files (bubble-card.js.gz, bubble-card.js, and bubble-pop-up-fix.js (downloaded from v3 beta 2)

1. I created under www a bubble-card folder, didn't work
2. Moved them just into the www folder, didn't work either
3. updated the version in the ressource path to v=3 or v=3.0.0-beta.3 as mentioned within the bubble-card.js file

**Comment by Peethiplatsch** [comment]
@Clooos I am just stupid. I moved it into the www/commnity folder because VScodeserver always opened that one. But now its working and I can select the type and configure it.

**Comment by Clooos** [comment]
Nice! Thank you so much for the feedback! One major issue fixed! 😃 

I will release a new beta soon, but I want to fix some pop-up issues first.

**Comment by Peethiplatsch** [comment]
Yes it showed beta3. I also had the new options for the sliders etc.

**Comment by Peethiplatsch** [comment]
I already did 😂

**Comment by Clooos** [comment]
The new beta is here!

https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-beta.3

**Comment by Peethiplatsch** [comment]
Works like a charm - for me. Thanks a lot mate.

**Comment by thrunkmo** [comment]
![Image](https://github.com/user-attachments/assets/8aaff4db-585f-4f6c-829a-d39306739e05)

Odd issue here after beta 3! Updated to the newest beta--hard reloaded the cache/restarted HA. Should I uninstall and reinstall Bubble Card as well? I did not install that Zip fix, just waited for this version to be released
