### ISSUE TITLE
Close PopUp menus not working correctly on Iphone

### ISSUE THREAD

**Issue by julien94800** [Clooos/Bubble-Card#1420]
**Describe the bug**  
When I open a popup menu on my iphone (either from chrome or HA app), in most of the case the close button do not work and I stay stuck in the popup menu. On a computer, everything working fine
**To Reproduce**  
1. Open any popup menu
2. Tap on the close button and nothing happens

**Expected behavior**  
Popup menu closed

**Informations (please complete the following information):**  
 - OS: 18,4,1
 - Browser/App: Chrome
 - Bubble Card version: 3.0.0 beta 1
 - Home Assistant version: 2025.4.3

**Additional context**  
I'm using horizontal button stack (not sure if linked or not)

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! Thank you for the feedback! This issue should be now fixed in this new beta 🙂 

https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-beta.2

**Comment by julien94800** [comment]
Hi @Clooos 
I just tried beta2 but issue is still present for me

**Comment by julien94800** [comment]
I just noticed that horizontal button stacks don't work anymore now

**Comment by rononline** [comment]
Same here! Can't close popups on IOS, and the horizontal stack doesn't follow it's links.

**Comment by Clooos** [comment]
I will check that, I was sure this was fixed 😅

**Comment by julien94800** [comment]
> I will check that, I was sure this was fixed 😅

Thanks a lot!! If anything I can do to help you identifying issue please let me know!

**Comment by Clooos** [comment]
The new beta is here 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-beta.3

**Comment by julien94800** [comment]
Hello @Clooos 
I just performed first test! Horizontal stack working back, and closing popup looks to be working too now!
I will try to play a bit more with it later today to cross check if all good!
THANKS A LOOOOOOOT

**Comment by Clooos** [comment]
Thank you so much for the fast feedback! 😄

**Comment by Clooos** [comment]
Nice! Thanks to you too!

**Comment by oerix** [comment]
I'm having a similar issue, however it only occurs with this particular popup for some reason.
I tried recreating it and tested on all browsers/devices, but get the same issue in beta-3. Only swipe down works, but even that is glitchy.

```type: custom:bubble-card
card_type: pop-up
hash: "#modes"
button_type: name
show_last_changed: false
show_attribute: false
margin_top_mobile: 20px
shadow_opacity: "30"
name: Modes
icon: mdi:auto-mode
hide_backdrop: true
entity: sensor.home_mode_status
margin: 7px
card_layout: large
show_header: true
bg_opacity: "88"
bg_blur: "10"
trigger_close: false
button_action:
  tap_action:
    action: none
  double_tap_action:
    action: none
  hold_action:
    action: none
close_on_click: true
show_icon: true
backdrop_blur: "10"
modules:
  - default
icon_container_color:
  color: none
```

**Comment by Clooos** [comment]
And no issue with this exact same pop-up before v3.0.0?

**Comment by oerix** [comment]
> And no issue with this exact same pop-up before v3.0.0?

Yup, worked perfectly fine pre v3. Clearing cache didn't help either.

**Comment by Clooos** [comment]
Do you have the same issue, with the same pop-up settings, but with no other cards in this pop-up?

**Comment by oerix** [comment]
> Do you have the same issue, with the same pop-up settings, but with no other cards in this pop-up?

Yes, even when the popup inside is empty. I also noticed that 'clicking outside' also doesn't work.

**Comment by Clooos** [comment]
Good to know! I will try to reproduce this then 🤞

**Comment by Clooos** [comment]
I just tried and I'm unable to reproduce this, but I might have fixed this by fixing some other issues 🤞

We'll see in the next beta, keep me informed! 🙂

**Comment by oerix** [comment]
> I just tried and I'm unable to reproduce this, but I might have fixed this by fixing some other issues 🤞
> 
> We'll see in the next beta, keep me informed! 🙂

Still present in beta 4. :( Not sure if it's any help, but here's the console log:

<img width="2354" alt="Image" src="https://github.com/user-attachments/assets/e2023a95-2228-4f7b-9f78-879bbe34aa84" />

**Comment by Clooos** [comment]
Are you sure that your config is correct? This error means that you have a pop-up card outside of a vertical stack.

**Comment by oerix** [comment]
> Are you sure that your config is correct? This error means that you have a pop-up card outside of a vertical stack.

Yep, It's inside (see below). It's kind of strange really as it doesn't affect all cards. I'm still trying to troubleshoot what the issue may be, will keep your posted.
```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
...
```

**Comment by Clooos** [comment]
Try to find what is causing the error you have in the browser console, this should helps a lot.

**Comment by oerix** [comment]
> Try to find what is causing the error you have in the browser console, this should helps a lot.

I managed to fix the issue! It seems that HA automatically removes the quotations when using `"/lovelace/#<popup>"` in the navigation path. However, the popup still triggers, but you get the issue above where you're unable to close it properly. I had to change it to just `"#<popup>"` to get it working.

Seems like the browser console issues were unrelated, but I still resolved them nonetheless.

Appreciate your help! :)
