### ISSUE TITLE
Media Volume Slider No Longer Showing Fill Color on v3.0.0 Beta

### ISSUE THREAD

**Issue by ilovepancakes95** [Clooos/Bubble-Card#1429]
Updated to v3.0.0-Beta3 from latest v2 release and before the update, slider cards used for media player volume would show the slider filled with background color (blue) from the left up to the setting (i.e. if volume set to 40%, slider would be 40% "full" with blue color).

Now after the update, the "fill" only shows when actively dragging the slider to adjust volume. When releasing the slider, the entire slider just shows the background color and not the "fill" at all.

I tried adding a slider with a light entity and it does work there (slider filled with % setting using current color of light), so seemingly something related to media player entities only.

**Comment by Clooos** [comment]
Hi! Thank you for the feedback, I will check that!

**Comment by ilovepancakes95** [comment]
So, I *think* it might be working okay now. I tried everything yesterday, I deleted and re-added the card from scratch, I restarted HA, I rebooted HA, I cleared frontend cache, I cleared browser cache, nothing worked. This morning, I reloaded the Sonos media player integration from within Music Assistant and now the sliders seem to work normally. I will continue testing in depth and report back if more issues still.

**Comment by Clooos** [comment]
Ok good to know, because I was totally unable to reproduce this 😄

**Comment by ilovepancakes95** [comment]
OK, played with this a little more and was able to isolate it to not working when the media player entity is not playing/idle state. The fill goes away when the media player is paused and comes back when playing again. I didn't see a setting to change this behavior and it did not seem to do this in v2 bubble card. Whether the player is playing or not, the volume attribute is still whatever it was set to, it doesn't drop to 0 or something, so why would the slider fill go away?

I am guessing this is because with a light slider, you want the card fill to go away when the light is off, which makes sense. Is there a way to get the volume slider to constantly display the fill regardless of media player entity state? I guess if I was using these sliders as a combined media player control card and volume slider, it would make sense to make the fill go away when the player is not playing, but in my case at least I have a bank of these sliders under a "Zone Volumes" heading and they are only meant to adjust the volume of each zone, even if no music is playing so it is quick to see what each zone is set to.

**Comment by Clooos** [comment]
Thank you for that detailed feedback! I was suspecting something with this slider, but I was never able to isolate this issue. 

I will check this for the next beta!

**Comment by ilovepancakes95** [comment]
Thanks, let me know if you need me to try anything else to help debug it. I am 99% sure it didn't do this on v2 because I paused music all the time and never saw the fill go away. Side note too, while I have you... THANK YOU for all the fantastic work on this card, it's really great. 😃

**Comment by Clooos** [comment]
Can you try to add this to the default module?

```yaml
* {
  --bubble-accent-color: var(--accent-color);
}
````

If it works, this means that this is already fixed on my side 🤞

**Comment by ilovepancakes95** [comment]
No dice. I think I did it correctly, as I see the following now in the "Default" module via card editor GUI, but the volume sliders still don't show the fill level unless actively being adjusted, or if the media playing is actively playing sound.

![Image](https://github.com/user-attachments/assets/b3a45d0e-d049-4f44-94b1-bdd372e39545)

**Comment by Clooos** [comment]
Ok, thank you for the feedback, I will check that then 🙂

**Comment by Clooos** [comment]
I found the cause! This will be fixed in the next beta 😄

**Comment by Clooos** [comment]
The new beta is here 😄

https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-beta.5

**Comment by ilovepancakes95** [comment]
Nice! Quick test does seem like that resolved it.

**Comment by Clooos** [comment]
Nice! Thank you so much for the quick feedback!

If there’s still an issue, let me know, and if everything works fine, let me know too! 😄

**Comment by ilovepancakes95** [comment]
Still seems good, so closing this out! Will let you know if something else crops up. As always, thank you!
