### ISSUE TITLE
custom element doesnt exist: bubble-pop-up

### ISSUE THREAD

**Issue by DaveTiff** [Clooos/Bubble-Card#1444]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
Works ok on Android Phone & PC Web browsers, get this message ONLY on Fully Kiosk V 1.57.1

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

![Image](https://github.com/user-attachments/assets/a045c812-a2ac-408c-bf1c-33b75a6ee5a6)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#pop-up-navigation"
  - square: false
    type: grid
    cards:
      - type: custom:button-card
        name: Home
        icon: mdi:home
        styles:
          card:
            - height: 60px
            - width: 150px
            - font-size: 12px
        tap_action:
          action: navigate
          navigation_path: /dashboard-mobile/heating
      - type: custom:button-card
        name: Heating
        icon: mdi:radiator
        styles:
          card:
            - height: 60px
            - width: 150px
            - font-size: 12px
        tap_action:
          action: navigate
          navigation_path: /dashboard-mobile/heating
    columns: 2
```

**Informations (please complete the following information):**  
 - OS: Fire Tablet
 - Browser/App: Fully Kiosk V 1.57.1
 - Bubble Card version: 2.4.0
 - Home Assistant version: 2025.4.4

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! This is a common HACS issue after some updates, check this [comment](https://github.com/Clooos/Bubble-Card/issues/1417#issuecomment-2832500555), these steps should fix this issue (I know the link point to a different issue, but this is the same solution).

**Comment by DaveTiff** [comment]
Hi, Tried changing the number, rebooted HA & Fire tablet, still the same error message?

**Comment by Clooos** [comment]
Try to uninstall/install it in HACS.

This issue has been reported so many times, if that don't works, search in the open and closed issues 🙂
