### ISSUE TITLE
State attributes for sensor.bubble_card_modules exceed maximum size of 16384 bytes

### ISSUE THREAD

**Issue by oerix** [Clooos/Bubble-Card#1566]
**Describe the bug**  
Starting seeing this in HA Logs: `State attributes for sensor.bubble_card_modules exceed maximum size of 16384 bytes`. Also, noticed poor performance when loading certain popups, they drop frames when opening.

**To Reproduce**  
1. Check HA Logs

**Expected behavior**  
Run smooth, with no performance issues.

**Screenshots**  

<img width="1110" alt="Image" src="https://github.com/user-attachments/assets/d6448b38-f962-4ac5-be04-03ffc11d2106" />

**Informations (please complete the following information):**  
 - OS: macos 15.5
 - Browser/App: Zen 1.12.10b (Firefox 139.0.1)
 - Bubble Card version: v3.0.0-Beta.9
 - Home Assistant version: 2025.5.3

**Additional context**  
```
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:663
integration: Recorder (documentation, issues)
First occurred: 18:35:48 (2 occurrences)
Last logged: 18:35:50

State attributes for sensor.bubble_card_modules exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
```

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! This warning can be ignored, the history of that entity will not be stored, that's all 🙂

But there is a way to fully remove it from the recorder, this way this message will not be displayed anymore. 

Check this:

https://www.home-assistant.io/integrations/recorder/#exclude

For the pop-ups, I will check what I can do👌

**Comment by Clooos** [comment]
Done!

<img width="275" alt="Image" src="https://github.com/user-attachments/assets/182dc6e4-4001-4a81-b69c-01e378c86010" />

**Comment by oerix** [comment]
> Done!
> <img alt="Image" width="275" src="https://private-user-images.githubusercontent.com/36499953/452091043-182dc6e4-4001-4a81-b69c-01e378c86010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDkyMjI2MzEsIm5iZiI6MTc0OTIyMjMzMSwicGF0aCI6Ii8zNjQ5OTk1My80NTIwOTEwNDMtMTgyZGM2ZTQtNDAwMS00YTgxLWI2OWMtMDFlMzc4Yzg2MDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjA2VDE1MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNDAwN2VmYzYxZjEyZDlkMzA2ODUyMTBmYjVlN2EyMDM4MTJiMjEwNzkyYzIxZDZjNDJiZDkzNGIyOThiMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wmevq4bZhHj4HWGPsxx8lNyDYMqonE7bTJI-bgPuPxU">

Thank you! :)

**Comment by scw2wi** [comment]
I have tried to exclude this sensor from the recorder but still get the Warning messages.

```
recorder:
  exclude:
    entities:
      - sensor.bubble_card_modules
```

Has anybody successfully supressed the warnings?

Update: Sorry, my fault, reboot was missing.

**Comment by przeniek** [comment]
v3.0.4 and still get errors

**Comment by drschnalli** [comment]
Hey there i'm on 3.2.5 and i still got this issue 
`State attributes for sensor.bubble_card_modules exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored`
