### ISSUE TITLE
Dropdown elements don't work

### ISSUE THREAD

**Issue by interkelstar** [Clooos/Bubble-Card#1586]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
When I click on any element that should provide popup dropdown list it is not appearing and there's an error in the console

![Image](https://github.com/user-attachments/assets/a7b1a92c-afef-4037-a52e-3e8e98611390)

![Image](https://github.com/user-attachments/assets/c4a34726-77e6-4adf-b460-dc6882d7e8e4)

**Comment by dvelaren** [comment]
Same error....
```
bubble-card.js?hacstag=680112919240:2 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at HTMLDivElement.<anonymous> (bubble-card.js?hacst…80112919240:2:30590)
(anonymous)	@	bubble-card.js?hacstag=680112919240:2
````

**Comment by keisersuze** [comment]
Same error.

**Comment by andreaconfa** [comment]
Same issue. cannot open any dropdown menu. in my case this is related to the "HVAC Modes" for the climate entities.

```
bubble-card.js?hacstag=6801129193009:2 Uncaught TypeError: Cannot read properties of null (reading 'hasAttribute')
    at HTMLDivElement.<anonymous> (bubble-card.js?hacstag=6801129193009:2:30725)

```

**Comment by mikechefy** [comment]
Had the same issue. Updated version 3.0.0-beta9 and issue is resolved. Hope this helps

**Comment by simwess** [comment]
I have the same problem and the update to 3.0.0-beta-9 has not solved the problem. It seems to have something to do with the current Home Assistant version. A downgrade to 2025.4.x solves the problem.

**Comment by cheringCode** [comment]
Just started using Bubble cards and I'm having the same issue with Fan modes dropdown within the Climate card.

```
bubble-card.js?hacstag=680112919240:2 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at HTMLDivElement.<anonymous> (bubble-card.js?hacstag=680112919240:2:30590)
```

**Comment by rnetz** [comment]
Same issue with v3.0.0-rc.1 on Android 15, using Card type Select, on both HA 2025.5.3 and 2025.6.1.
```
Uncaught error from Chrome WebView 137.0.7151.90 on Android 15 TypeError: Cannot read properties of null (reading 'setAttribute') HTMLDivElement.<anonymous> (/hacsfiles/Bubble-Card/bubble-card.js:2:30590)
```

Please let me know if there is anything else I can provide or test

**Comment by Clooos** [comment]
Hi, this issue is fixed in latest pre-release, here's the changelog:

https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-rc.3

@rnetz There is also currently an issue with HACS causing some updates to download the wrong version, check in the Bubble Card editor if you see the correct version.

**Comment by rnetz** [comment]
Just checked it out and rc3 works. Thanks!
