### ISSUE TITLE
Min max volume slider not working

### ISSUE THREAD

**Issue by niewe2** [Clooos/Bubble-Card#1599]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
I have the latest beta and latest HA update. But the min max for the volume slider does not work. Is that correct? Does this need a fix or am i doing something wrong? 

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Your code here
```

**Informations (please complete the following information):**  
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4]

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! This was indeed an issue, but I just fixed it and this will be part of the next pre-release 🙂 

Thank you for the feedback!

**Comment by Clooos** [comment]
The new release is here, tell me if everything works for you now 🙂 

https://github.com/Clooos/Bubble-Card/releases/tag/v3.0.0-rc.3

**Comment by niewe2** [comment]
Nop, min max volume still not working in 3.0.0-rc.3 with HA 2025.6.3.

**Comment by Clooos** [comment]
Can you check in the editor if you see the correct version? Some updates with HACS are not downloading the correct version.

Edit: You're right, it doesn't works inside of the media player card, it was not working in the sliders as well (and this is fixed there), I will fix this right now.

**Comment by niewe2** [comment]
Both HACS and editor show: Bubble Card v3.0.0-rc.3

**Comment by Clooos** [comment]
If you haven't seen my edit:

You're right, it doesn't works inside of the media player card, it was not working in the sliders as well (and this is fixed there), I will fix this right now.

**Comment by niewe2** [comment]
Haha awesome support on this card <3 
Insanely user friendly and the nicest looking card

**Comment by Clooos** [comment]
Thank you for the kind words! ❤️

And this is fixed on my side, just wait for the next release 😄

**Comment by niewe2** [comment]
And indeed. Nicely fixed!

**Comment by Clooos** [comment]
Have fun with v3.0.0 now 😄
