### ISSUE TITLE
Lock card showing closed when it's open

### ISSUE THREAD

**Issue by Lk1975** [Clooos/Bubble-Card#1874]
Adding a sub button of a lock entity it shows locked when it's not. Tried to remove and re-add and to choose another lock from another integration but it has the same behaviour.
Bubble card is the last version, HA OS version 2025 10.1

**Comment by Lk1975** [comment]
still no clue?
It's really annoying, because at first glance it's showing the incorrect state

**Comment by Clooos** [comment]
Hi! I will check this for the next release 👌

**Comment by Lk1975** [comment]
Thanks a lot! just to be more specific, the issue is on the Background color based on state, it's coloured when the lock is open instead of when it's closed.

**Comment by Clooos** [comment]
I just checked and this is the expected behavior (this was a reported issue), but it would probably be better to make the background color red instead when it's unlocked, what do you think ?

**Comment by Lk1975** [comment]
I don't know since what version it changed behaviour but I can assure you this is not the expected behaviour, or at least it wasn't. I use in the button group, and  I use to monitor my casts. 

￼

as you can see both of my cats are at home and the button is colorued. vicersa the lock is unlocked and it’s colorued. Before it was white. How is possibile to manage the behaviour?

**Comment by Lk1975** [comment]
Ok, found it. with version 2.3.4beta1 it was fine:

￼

**Comment by Clooos** [comment]
I don't see your screenshots

**Comment by Lk1975** [comment]
￼￼

can you see it now?

**Comment by Lk1975** [comment]
<img width="504" height="71" alt="Image" src="https://github.com/user-attachments/assets/62600a94-2fc8-4ae2-8f15-8d8b9ede8275" />
<img width="504" height="71" alt="Image" src="https://github.com/user-attachments/assets/03ea81b5-2414-4d13-bf26-bfec289adc9d" />

**Comment by Lk1975** [comment]
the one in orange is 2.3.4beta1, the one in blu is the actual version

**Comment by xoatrash** [comment]
Let me add: when the door is "Unlocked", it still shows the "Lock" icon.
Default HA tile card shows the icon correctly, but in Bubble Card not.

**Comment by Clooos** [comment]
@xoatrash Oh indeed I forgot to fix this indeed.

**Comment by Lk1975** [comment]
Did you manage to fix it?

**Comment by Clooos** [comment]
@Lk1975 This issue should be fixed in Bubble Card v3.1.2, have you tried it?

**Comment by Lk1975** [comment]
Unfortunately it's still the same. device is unlocked and the color is read. In the meantime I am using this code to override the color: |
  .bubble-sub-button-3 {
     background-color: ${hass.states['lock.gattaiola_locked_in'].state === 'locked' ? 'red' : '#4CAF50'} !important;
   }

**Comment by Clooos** [comment]
If I understand your issue correctly, you want the red color when your entity is locked? This looks like a bit unintuitive, the fact that it is red is to highlight (for example) when your car or your house is unlocked. What use case would imply to have it red when locked?

**Comment by pos-ei-don** [comment]
I have the Same iasue. For example when the precence Sensor in the Floor isbmanually locked(=disabled) , this isbnot the normal state and so it should be Red.

**Comment by Lk1975** [comment]
> If I understand your issue correctly, you want the red color when your entity is locked? This looks like a bit unintuitive, the fact that it is red is to highlight (for example) when your car or your house is unlocked. What use case would imply to have it red when locked?

The colour doesn't matter, if you see in my previous post, with version 2.3.4beta1  or earlier, when lock was unlocked, the button was white, and was coloured only when locked. In that way it was very intuitive, with an eye glance I know if the cat were locked inside the house.

**Comment by Clooos** [comment]
I don't know what to do here 😅 I got so many feedback asking for turning it red instead of blue (so the total opposite as what you ask here), this is the same color HA use for unlocked states, so I guess using custom styles like the @Lk1975 example is the best way.
