### ISSUE TITLE
Freeze on config change

### ISSUE THREAD

**Issue by man010** [Clooos/Bubble-Card#1936]
Hello, first thanks a lot for this wonderful cards. I am using it extensively, especially for the popup menus.

It appears that since version 3.0.0, when a dashboard has multiple popups, and I change the config of a card, the application freezes on my iPhone after a click on « save »… there is a wheel turning endlessly in the save button. The only thing I can do is kill the app and relaunch it… the good thing is that the changes have been saved anyway. This behavior has occurred with versions 3.0.4 and 3.0.1.

So I reverted to bubble card 2.4.0, with no other change, and the issue is gone…

Here is my config :
- Méthode d'installation
Home Assistant OS
- Core
2025.11.3
- Supervisor
2025.11.4
- Operating System
16.3
- Interface utilisateur
20251105.1
- Application Companion
2025.10.0 (2025.1443)

My iPhones are 12 Pro Max and 15 Pro ( same issue on both)

**Comment by Clooos** [comment]
Hi! I've just released Bubble Card v3.1.0-beta.1, could you maybe give it a try? I've fixed a lot of pop-up issues in this version 🙂

https://github.com/Clooos/Bubble-Card/releases/tag/v3.1.0-beta.1

**Comment by man010** [comment]
Thanks but still not working

![Image](https://github.com/user-attachments/assets/11bbec53-5969-492e-988b-c2cd9304a8c6)

**Comment by Clooos** [comment]
Have you cleared the cache? Do you see v3.1.0-beta.1 at the bottom of the editor?

**Comment by man010** [comment]
Yes I installed successfully the version, but the problem remained, I fell back to 2.4.0.

**Comment by Clooos** [comment]
Sorry to hear that, I will check if I can reproduce this on an iOS device.

**Comment by Freshhat** [comment]
Even in Chrome with the latest beta 4 it's freezing. I'm getting a lot of these errors in the Console:
Cache expired but kept for potential API limit situations

Currently in the latest beta i can't change anything

**Comment by Clooos** [comment]
Thank you for the error, I will see why it's slowing down your dashboard this much 👌

**Comment by Clooos** [comment]
Hi! Just wanted to know if this is still an issue with beta 7?

**Comment by man010** [comment]
Yes still the same issue

<img width="590" height="1278" alt="Image" src="https://github.com/user-attachments/assets/6ec4d038-65ab-45af-92a2-5dd1d63d0241" />

**Comment by Clooos** [comment]
I just realized something, you are using `custom:button-card` and not `custom:bubble-card`, please open an issue on the right GitHup page:

https://github.com/custom-cards/button-card

**Comment by man010** [comment]
The issue seems to be with the bubble card pop-ups. I have the same issue with all the cards when using bubble card v3.. so I fell back to v2 and I can modify all the cards without any timeout

**Comment by man010** [comment]
Same issue with apexchart when running v3 or above

<img width="590" height="1278" alt="Image" src="https://github.com/user-attachments/assets/4e848bfc-bd99-4e44-9a39-5ef8974659fa" />

**Comment by man010** [comment]
Well actually the issue also appears  with v2.5b9. Since v2.4 is no longer available can you please put it back ? It seems to be the last version that does not suffer from this bug…

**Comment by Clooos** [comment]
Oh ok, then wait a bit for the next beta, this could fix your issue 🙂
