### ISSUE TITLE
[Media card] Card name not visible

### ISSUE THREAD

**Issue by zulufoxtrot** [Clooos/Bubble-Card#1950]
**Describe the bug**  
Observed on the latest beta (v3.1.0-beta.1)
Unsure if this is a regression, because I started using this card type after switching to this version.
The name of the card (ex: Living Room Stereo) is not visible on the card, even if the option is ticked. See screenshot.

**To Reproduce**  

1. create bubble card
2. pick "media player"
3. tick "show name"

**Expected behavior**  
The name is visible if defined.

**HA logs**  
If applicable.

**Browser console logs**  
If applicable.

**Screenshots**  

<img width="1013" height="704" alt="Image" src="https://github.com/user-attachments/assets/53328e2f-035c-4bf4-8561-7fa310dcc38c" />

**YAML**  
If applicable, add any relevant YAML code.

```yaml
type: custom:bubble-card
card_type: media-player
button_type: switch
entity: media_player.home
name: Media Player
```

**Information (please complete the following information):**  
 - OS: [e.g. iOS] MacOS
 - Browser/App: [e.g. chrome, safari] FF 144.0.2
 - Bubble Card version: [e.g. 2.0.4] v3.1.0-beta.1
 - Home Assistant version: [e.g. 2024.6.4] 2025.11.2 / frontend 20251105

**Comment by Clooos** [comment]
Hi! I realized that today as well on my own media player card, this was a mistake on my side. This will be fixed for the next beta 👌

**Comment by zulufoxtrot** [comment]
Great to hear!

Just in case, I tested more cases and it appears that the name and "main" value depend on the player state. Video below.

![Image](https://github.com/user-attachments/assets/39806cd2-dd3f-4b90-95b0-e3e4c8c9ab99)

**Comment by Clooos** [comment]
Thanks, but I was aware of that and I just fixed it on my side (the changes I've made for the cover transitions caused it), now just wait for the next beta 😄

**Comment by Clooos** [comment]
And done! Here is the release! 😄

https://github.com/Clooos/Bubble-Card/releases/tag/v3.1.0-beta.3

**Comment by zulufoxtrot** [comment]
Thanks! I just tested beta 4, but I can still reproduce the issue:

<img width="986" height="586" alt="Image" src="https://github.com/user-attachments/assets/96c2a0f4-98c5-4348-80a6-94b3cc7cddd5" />

What i tried:
- Force refresh page
- HA quick reload

**Comment by Clooos** [comment]
This is the expected behavior, your media player is in "playing" state and so the title is shown instead of the name/state. The name/state is only shown when the entity is off/idle or when there is no title/artist to display.

**Comment by zulufoxtrot** [comment]
Hi! Tthe missing name was the point of my ticket, so I'm a little confused because I don't understand what you fixed then :D 

Let me rephrase. I think that when the player is in "playing" state AND there is no artist name available, then the card should display (Name of device + Available info):

<img width="509" height="67" alt="Image" src="https://github.com/user-attachments/assets/ac546604-09eb-4a53-a9d0-b096db72489c" />

Or (Available info) twice:

<img width="506" height="71" alt="Image" src="https://github.com/user-attachments/assets/e6d7b06e-ae85-45f7-9a37-d8f7cdff376f" />

Instead of this:

<img width="435" height="72" alt="Image" src="https://github.com/user-attachments/assets/df3dd47e-cf5b-417e-b22b-c065d1101f46" />

For comparison, Mushroom can achieve what I want with a bit of customization:

```yaml
type: custom:mushroom-media-player-card
entity: media_player.home
use_media_info: true
name: Media Player

```

<img width="489" height="79" alt="Image" src="https://github.com/user-attachments/assets/73d83078-bcb7-4442-8f68-fc8139a8885f" />

**Comment by Clooos** [comment]
In fact this change was caused by an Home Assistant update, the source name has been added as the media title as well, that's why it was detecting a title and was showing this only. 

But I've fixed that, just wait for v3.1.0-beta.5 (I should be able to release it today).

**Comment by mgraebi** [comment]
> In fact this change was caused by an Home Assistant update, the source name has been added as the media title as well, that's why it was detecting a title and was showing this only.
> 
> But I've fixed that, just wait for v3.1.0-beta.5 (I should be able to release it today).

Unfortunately, the name is not displayed in version 3.1.0 either.

**Comment by Clooos** [comment]
It is displayed only when the media player isn't playing. But I understand this can be confusing and I will probably change that in an upcoming release.
