### ISSUE TITLE
I can’t get into the module store anymore

### ISSUE THREAD

**Issue by Pscharumbel** [Clooos/Bubble-Card#2036]
It gets stuck on ‘Checking API limits,’ and the percentage indicator just keeps spinning.
How can I provide you with more information?

**Comment by Pscharumbel** [comment]
Oh, now it worked after all—without me changing anything.

**Comment by Clooos** [comment]
Was the refresh longer than usual?

**Comment by klaptafel** [comment]
Same here, it's going nuts!

https://github.com/user-attachments/assets/edbaa635-3ccb-4b3e-bb6b-6ec4785fc0c1

**Comment by Clooos** [comment]
WTF 😅

I will release a new version to fix this the sooner than I can!

**Comment by Pscharumbel** [comment]
Yes, it was longer

**Comment by shelly20222** [comment]
same on my side. Looking forward for a fix :-) Merry christmas

**Comment by thai-byte** [comment]
My first time trying to do something fancy in Home Assistant and I thought I messed up as I get the same craziness with API limits. Looking forward to the fix

**Comment by Clooos** [comment]
I just fixed this, I will try to release a new version today or tomorrow, in the meantime you can still install the previous beta 🙂

**Comment by shelly20222** [comment]
I have installed v3.1.0-beta.8 but I am still not able to go to module store. Am I doing something wrong?

<img width="474" height="852" alt="Image" src="https://github.com/user-attachments/assets/a6c7d13b-b021-4de7-bb41-82854b753f9a" />

**Comment by shelly20222** [comment]
after a few moments (going to take coffee) it is working now

**Comment by shelly20222** [comment]
<img width="835" height="872" alt="Image" src="https://github.com/user-attachments/assets/a4e71d52-5bdc-4589-bd9d-3e8adbab6623" /> today again, even coffee has not helped. Do you have any idea if it is only on my side @Clooos ?

**Comment by Clooos** [comment]
Hi! Could you check in your browser console if you see any error or warning?

**Comment by shelly20222** [comment]
everytime after writing here it is working ;-) next time I will check browser console immediately :-) thank you

**Comment by Clooos** [comment]
It's also possible that your internet connection is unstable when it happens, or even that the GitHub servers are a bit overloaded, but in beta.8 it should handle these cases more properly.

But I would be interested to see your logs if it happens again 🙂

**Comment by shelly20222** [comment]
Happens every day again. Here the screenshots to it:

<img width="1876" height="892" alt="Image" src="https://github.com/user-attachments/assets/41f325eb-00d8-4117-a467-d9ea29a111a1" />

<img width="1876" height="892" alt="Image" src="https://github.com/user-attachments/assets/13413e90-08aa-4677-bd06-2cf898e2840d" />

**Comment by Clooos** [comment]
Are you updating the Module Store multiple times repetitively?Because there is indeed an API limit if you refresh it too often (you then need to wait 1 hour).

But a warning should be shown in that case, I will see why it is not shown for you.

**Comment by shelly20222** [comment]
I have started work today, want to create bubble cards with the module store. Haven't started it since yesterday. 

Now, after trying again, it is there: 

<img width="943" height="873" alt="Image" src="https://github.com/user-attachments/assets/3b1e5492-dc80-4adb-94e1-27f2dff89935" />

**Comment by shelly20222** [comment]
today it is working immediately 😄

**Comment by Clooos** [comment]
Now that you have everything in the cache it should works correctly for good, but indeed there is an issue if this is the first time you're opening the Module Store, I should have fixed this for good 🙂

**Comment by shelly20222** [comment]
looks great <img width="461" height="635" alt="Image" src="https://github.com/user-attachments/assets/ceb751c0-022c-4b96-9745-0c0efd9020f9" />

**Comment by Clooos** [comment]
Nice! I'm glad to close this one! 😁
