### ISSUE TITLE
Large Dashboards crashed the ios App

### ISSUE THREAD

**Issue by cryd-s** [Clooos/Bubble-Card#213]
Hi,
i have decided to create my dashboard with the bubble card.
On the browser on my pc it works fine but if i want to open it on the iPhone the app hangs up and restart non stop.

I think there is to much on one dashboard. 

Is there a way out how i can fix this - reduce content is no option :(

**Comment by lexusburn** [comment]
Hi,

i have a dashboard with 33 pop-ups in 6200 lines of yaml for the dashboard and it's working fine with latest version (1.5.3) and optimized mode (module loaded in configuration.yaml) on desktop and ios app.

How many popups and lines of code for the dashboard do you have?

Have you checked that you don't have invalid entities? 
There's a known problem, if you have some (have a look on the issues).

**Comment by cryd-s** [comment]
How can i check for invalid entities?

**Comment by lexusburn** [comment]
Install watchman (https://github.com/dummylabs/thewatchman) and check with it for invalid/missing entities.

Other hint: open a desktop browser and have a look into the web console for errors. If you have some there, try to fix and/or show us the problems and we could try to help.

**Comment by cryd-s** [comment]
![image](https://github.com/Clooos/Bubble-Card/assets/47699362/df0df736-6d45-47c9-bf4a-3441eb8bc5e1)

Thats my watchman report.
I think it looks clean cause line 23-26 are still examples.

**Comment by cryd-s** [comment]
![image](https://github.com/Clooos/Bubble-Card/assets/47699362/2e96e6f4-284f-42db-9eac-56bbac5e3e55)

got this in my browser console but dont know where to find this

**Comment by cryd-s** [comment]
https://github.com/Clooos/Bubble-Card/assets/47699362/6d49f599-036f-4498-be6d-7b87c5e13eb7

a reinstall of the app doesnt fix my problem

**Comment by cryd-s** [comment]
[raw.txt](https://github.com/Clooos/Bubble-Card/files/13501259/raw.txt)

I hope @Clooos can help me cause i want to make a yt video about this nice card

**Comment by cryd-s** [comment]
done but doesnt fix the problem

**Comment by cryd-s** [comment]
yes kiosk is removed from raw config and app is reinstalled

**Comment by cryd-s** [comment]
![image](https://github.com/Clooos/Bubble-Card/assets/47699362/738b830b-3552-4c82-960a-d581ea7f07c5)
this appears in the console when i switch from an other tab to the tab that provides problems

**Comment by cryd-s** [comment]
@Clooos sorry for tagging u but can u help me cause i want to create a video on my yt channel about this integration. 
Would be very nice from u

**Comment by Clooos** [comment]
Hi, your error is not a Bubble Card error, maybe a conflict with some other cards? Have you tried on a new blank view to try to understand what is causing this error?

**Comment by Clooos** [comment]
Can you tell me what specific Bubble Card makes this error on your dashboard? This will help me understand what can cause that in my code.

**Comment by cryd-s** [comment]
> Can you tell me what specific Bubble Card makes this error on your dashboard? This will help me understand what can cause that in my code.

no cause the problem is a little bit random. Once i have to delete 3 cards to get it working - the other time i had to delete 5 - and so on

i have tried to add once then testing - everything is fine - add another - everything is fine - add another then it doesnt work - but now it can be that i have to delete 4 to get it working.

I hope u understand what i mean. I can show u via discord if u want  - on desktop everything is fine - but ios app is crashing

**Comment by cryd-s** [comment]
> I'd say the best way to understand what is happening is to test it yourself by moving dashboard bit by bit and narrowing it down.

i did this several times but cannot figure out what the problem is

**Comment by cryd-s** [comment]
ok i give up. no chance to find the error. thanks for your tips

**Comment by Clooos** [comment]
Hi, can you try with the latest beta?

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.5

**Comment by lexusburn** [comment]
Have problems with new beta and ios. 
Try to debug it later...

**Comment by lexusburn** [comment]
@Clooos on chrome desktop i get this error in the javascript console:

<img width="622" alt="Bildschirm­foto 2024-01-04 um 19 12 06" src="https://github.com/Clooos/Bubble-Card/assets/659847/cf050356-f444-437b-8b39-1ad0ff557c55">
<img width="465" alt="Bildschirm­foto 2024-01-04 um 19 12 24" src="https://github.com/Clooos/Bubble-Card/assets/659847/b3c5fa7d-a1e2-4183-ad90-ce3c80ed6159">

**Comment by Clooos** [comment]
This is fixed in the new stable release! 🍻

**Comment by dsvdglenn** [comment]
The reloading issue is better since 1.6.4 but not solved. The issue comes back on limited internet connections and if I start scrolling the dashboard to soon after opening the HA app. No issues on iPad or desktop. Just the mobile app

**Comment by hellomarb** [comment]
My dashboard is still crashing on scroll even on 1.7.0. Last working version for me is still 1.5.3.

**Comment by Clooos** [comment]
Hi, this issue should be definitely fixed in the v2 beta! Can anyone confirm this?

Here is the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by hellomarb** [comment]
Yes, it is working fine with the new beta.
I started to use it since last week (before the "official release") and haven't any issues so far!
