### ISSUE TITLE
Beta v1.6 Won't load on Android Companion App

### ISSUE THREAD

**Issue by DerHerzog7** [Clooos/Bubble-Card#252]
Upgraded to beta 1.6 today. Got it running on iOS by reloading the cache. Couldn't get it running on Android companion app at all. It would just load a blank screen.

Tried deleting cache, then data then reinstalling the whole app. Wouldn't load until I reverted to v1.5.3.

**Comment by Clooos** [comment]
Hi and thanks for your feedback.

This issue should be fixed in the new 1.6.0-beta.2 🤞
https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.2

**Comment by DerHerzog7** [comment]
Issue is still occurring on beta 2. It actually showed up in 1.5.3 when I downgraded too. Not sure what's going on?

**Comment by DerHerzog7** [comment]
Just upgraded to beta 3. It appears to be an issue with the dashboard loading incredibly slowly on Android. 

I'm using optimised mode. Is it meant to be listed as v1.6.0-beta.3 in the config?

**Comment by Clooos** [comment]
Can you try in regular mode? I still don't understand your issue because It's really fast on Android on my side.

Have you checked in your logs if there are errors?

And I'm not sure to understand your last question.

**Comment by DerHerzog7** [comment]
Regarding the last question, is that the format I should be putting the version down as for beta versions? 

The logs aren't throwing anything up. The dashboard just seems to be loading really slow or not at all on my partner's galaxy phone. 

I'll try reloading it as regular version.

**Comment by DerHerzog7** [comment]
I wonder if it was the header I used from Mobile First. Since the card mod update I removed the graphic and image and things seem to be working quicker. I'll do some more testing...

**Comment by DerHerzog7** [comment]
I just had another look on my partner's phone. It still doesn't seem to be loading. Any thoughts?

**Comment by Clooos** [comment]
Can you try the latest beta?

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.5
