### ISSUE TITLE
Older IOS devices "Custom element doesn’t exist"

### ISSUE THREAD

**Issue by dwhall96** [Clooos/Bubble-Card#257]
Issue exists only on older IOS devices in my testing Card does not load with error "Custom Element doesn't exist", issue is not present on newer devices.

 I have tested 3 different IOS IPAD Air A1475 version 12.5.7 with the same results. I have cleared cache, deleted and reinstalled the IOS app and tested Chrome browser with the same results. I also installed an older version of the bubble card. 

These devices may be too old to consider supported but wanted to raise a issue in case it is a feasible fix.

**Comment by Clooos** [comment]
Hi and thank you for that interesting feedback!

Could you try to add this to your config?

frontend:
  extra_module_url:
    - /hacsfiles/Bubble-Card/bubble-pop-up.js?v=0.0.0
  extra_js_url_es5:
    - /hacsfiles/Bubble-Card/bubble-pop-up.js?v=0.0.0
    
Just replace 0.0.0 with your actual version.

**Comment by dwhall96** [comment]
![image](https://github.com/Clooos/Bubble-Card/assets/59123656/1fab24d2-c720-4a2d-9a4a-9bd42de4d76f)
I added the lines to the config as requested but the issue persists. 
to note I did restart HA, cleared cache and even tested multiple devices app and browser to confirm. 

This is happening with all bubble cards. I have setup only a few pop ups, separators and buttons for a test run, each have the Custom element doesn't exist errors on the older devices but work great on newer devices that I love (which is why I am reaching out). 

I want to add that the bubble card is not the only custom cards that are having the same issue on these old devices. While it is not all of the custom cards from HACS there are some that display the same error so this could be common and it is feasible it is on my side. As an example mushroom cards work fine as well as some slider cards and TV control but the issue is the same for a clock-weather-card I use. Googling this error takes me down a few paths so still on the testing phase to see if its fixable. Any help is appreciated but I understand if this is not something you can assist with.

**Comment by ModestoHagney** [comment]
Did you ever have any luck with this? I'm having the same issue on an old iPad mini I have as a wall mounted tablet.

**Comment by dwhall96** [comment]
No luck, I found that the old iPad architecture does not play nice with anything HA. There is a chance you can get it to a stable state but one update or change can cause more issues than it’s worth. Its sucks because I have a stack of old iPads that could use but I was forced to resort to cheaper android tabs.

**Comment by Clooos** [comment]
This is true for now, but I still hope to be able to makes it working on older devices.

**Comment by ModestoHagney** [comment]
Let me know if there’s any logs or info you need.

**Comment by Clooos** [comment]
It would be great, in your Home Assistant logs you should have some errors when Bubble Card is loaded on you view.

**Comment by ModestoHagney** [comment]
Sorry it's taken so long. I finally got around to actually looking into this. I loaded up the Dashboard I use on my phone on the iPad and had a look through the logs, I can't seem to fins anything relevant anywhere. What logs should I be looking looking at?

**Comment by Clooos** [comment]
Have you taken a look at the Home Assistant logs in Settings > System > Logs?

**Comment by ModestoHagney** [comment]
That’s where I was looking, I had the logs open while I loaded the dashboard. Reloaded the logs, went through a bunch of the different logs, couldn’t see anything relevant. I’ll try clearing the logs and looking again.

**Comment by Clooos** [comment]
Hi @dwhall96 and @ModestoHagney, I've released a new version that might fix this issue on older devices, can anyone confirm this?

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.3

**Comment by ModestoHagney** [comment]
Unfortunately this didn’t fix it for me, though I just went to the dashboard I use on my iphone and tried it on the iPad. 

When I get home from work I’ll try making a new dashboard with just one card and see what happens. 

I’ve attached a screenshot so you can see the error. 

![IMG_F1C79E63FDA1-1](https://github.com/user-attachments/assets/3583b364-4914-49bc-95d7-972328dc510a)

**Comment by Clooos** [comment]
Can you provide any logs related to the frontend in the HA logs, you should see one about bubble-card.js.

**Comment by ModestoHagney** [comment]
Last time I looked through the logs I couldn’t see any related to bubble card. I was probably looking in the wrong place, I’ll take another look tonight when I get home.

**Comment by Clooos** [comment]
None of them is directly mentioning Bubble Card, it's in frontend.js or something like that.

**Comment by Clooos** [comment]
Nothing related to Bubble Card, but there should be some logs that mention it somewhere.

**Comment by hhu94** [comment]
I'm seeing the exact same behavior as @ModestoHagney. I wonder if this is somehow related to https://github.com/home-assistant/frontend/issues/21004, which was fixed in the HA frontend two months ago.

**Comment by Clooos** [comment]
I have no idea, but even if I find a way to make it works on older devices, most of the CSS styles are too modern, and making it "visually compatible" would probably be a nightmare for me 😅 

To be honest this issue is likely the one with the lowest priority for me right now.

But if anyone can provide me any logs, from the browser console or from Home Assistant, I will try to makes it compatible, the CSS styles would be the next step.

**Comment by ModestoHagney** [comment]
I'm away from home at the moment so I can only grab logs from HA remotely at the moment sorry, but I doubt there will be anything relevant as it's not being used. If you let me know what logs you need, I can grab some while I'm back there in the weekend. I had a brief look through last time, but I couldn't find anything relevant. I assume I'm just not looking in the right place.

**Comment by dougrathbone** [comment]
I'm reporting this pretty broadly across devices. IPad 4, 2N Intercom (Android), and iPhone 10.

These arent brand new devices, but they also arent that out of date from an OS updates POV. The 2N device especially is quite new.

**Comment by ericcastro** [comment]
@ModestoHagney I think this should be given priority. a LOT of users actually use old ipad / iphones for home dashboards vs keeping them in drawers collecting dust.

this is -to me- one of the best use cases of HA giving old hardware a second life.

but... I believe this is a bug with home assistant and not the cards themselves, because I am getting it with other custom ones too

**Comment by ModestoHagney** [comment]
Since HA stopped supporting old versions of iOS i've given up with the old ipad. i thought about making a more simple dash for it but i use my phone most of the time anyway.

**Comment by ericcastro** [comment]
Actually, I was just digging in other cards having this issue and it DOES seem the problem can be fixed at the card level. Check this thread: https://github.com/piitaya/lovelace-mushroom/issues/1582

so HA definetly broke support for iOS 12 on their recent releases, but it can be fixed at the card level, apparently.

**Comment by ericcastro** [comment]
I confirm, mushroom has managed to fix this issue on iOS 12.5.7

**Comment by Clooos** [comment]
I've never said it was impossible to fix, and I'm in fact aware of the solution (like in the Piitaya's PR shared by @ericcastro), the major issue is that most of the Bubble Card CSS styles are too modern and even if I make it works with older browsers, a lot of styles wouldn't work as expected and making them compatible is a lot more work.

That's why I've said it has the lowest priority, but I will maybe work on this one day if I found some courage and more time 😅 But if someone experienced want to help me on this, he's more than welcome! 🙂

**Comment by raouldw** [comment]
I have this exact same problem on my new iPhone 16 with IOS 18.1.1

**Comment by pdawg17** [comment]
Huh I just started having this issue on Edge browser (Windows 11 and Pixel 9 phone)...

**Comment by Clooos** [comment]
> Huh I just started having this issue on Edge browser (Windows 11) and HA app on Android (Pixel 9)...

Hi, your issue looks more like this one, the solution is in it:
https://github.com/Clooos/Bubble-Card/issues/1243

**Comment by HorizonKane** [comment]
Just tried to repurpose an old iPhone mini and got this issue :(

**Comment by HorizonKane** [comment]
Did some more research. This is really frustrating. Just spent two days for a complete redesign of my dashboards using bubble card and I just love the result. And now I have to ditch it and start from Scratch :( because I am not going to spend hundreds of dolalrs on new tablets :(
