### ISSUE TITLE
HACS install issue

### ISSUE THREAD

**Issue by Z3r0XG** [Clooos/Bubble-Card#259]
Hello, I am trying to install via HACS.  If I search for "Bubble Card" and variations of those terms, or sort alphabetically, it does not show up.  If I try to add it via a custom repository, it says it already exists. The instructions do not seem to match the current version of HACS I have installed. Is there a compatibility issue?

**Comment by Clooos** [comment]
Hi, have you tried to restart your Home Assistant to let HACS renew the cache?

**Comment by Z3r0XG** [comment]
Hi yes, restarted/rebooted server.

**Comment by Clooos** [comment]
My first guess is that this is some kind of cache issue in HACS. The other only possibility is that your HA version is lower than 2023.9.0 because Bubble Card doesn't support these versions.

**Comment by mag1024** [comment]
I'm seeing the same thing with HA 2024.1.1.
Interestingly, adding a custom repository by github url doesn't work because HACS claims `Clooos/Bubble-Card` already exists in the store, but it is not actually findable in the list of frontend repositories.

**Comment by Clooos** [comment]
This is finally fixed! This was related to that [HACS issue](https://github.com/hacs/integration/issues/2736), but I've removed the country from the Bubble Card config so that there are no changes for the users to make. A reboot should fix that, or a 48-hour wait time according to the HACS developer.

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.2

**Comment by gabimal** [comment]
I still face the issue with missing Bubble Card in HACS. My setup:

Core 2024.1.1
Supervisor 2023.12.0
Operating System 11.3
Frontend 20240104.0

Any advice?

**Comment by Z3r0XG** [comment]
For me, I had to clear all HACs filters, then it popped up.

**Comment by Clooos** [comment]
Take a look at this, that should fixe your issue.

https://github.com/hacs/integration/issues/2736

**Comment by gabimal** [comment]
Before my previous message I had already tried with changing the HACS country and clear browser cache but it didn't work. In the meantime I upgraded HA OS to 11.4 and rebooted the system. Not sure if this was the issue but by magic the Bubble Card appeared in HACS.
Thank you for your prompt message!

**Comment by Clooos** [comment]
Glad that this is fixed! And you're welcome!
