### ISSUE TITLE
Pop Up Trigger not working

### ISSUE THREAD

**Issue by simensus** [Clooos/Bubble-Card#273]
Hi,

after the Updat to 1.6 (i guess) the Pop Up Trigger for my Security Card (One Camera Live Feed) is not working anymore.

![image](https://github.com/Clooos/Bubble-Card/assets/101661986/8e8672e2-a644-42ea-b104-91db187f8b31)

Thes are the settings

Bubble Card Version 1.6 Beta 4

**Comment by simensus** [comment]
even after updating to the latest Beta. 
When i open the popup with the camera feed i get the following errors in the developer console:

![image](https://github.com/Clooos/Bubble-Card/assets/101661986/121f8c1a-e33d-4617-bb34-b6f28f696e4d)

**Comment by Clooos** [comment]
This is fixed in the new stable release! 🍻

**Comment by simensus** [comment]
The Pop Up Trigger is still not working in my dashboard. I have a input_boolean as trigger with the state "on". But when i set the button to on, it is not working!
