### ISSUE TITLE
Custom upcoming media card formatting broken

### ISSUE THREAD

**Issue by wookash** [Clooos/Bubble-Card#356]
Custom upcoming media card's (https://github.com/custom-cards/upcoming-media-card) formatting is broken as per screenshot. Looks the same on PC / laptop and mobile. The card displays properly in optimised mode, but then this mode is now obsolete and the card can't be close when in optimised mode..

**To Reproduce**
click the button to open bubble card

**Expected behavior**
The custom upcoming media card's formatting should be correct

Screenshots
attached

Desktop
 - OS: macOS
 - Browser brave
 - Version 1.6.4

Smartphone 
 - Device: iPhone
 - OS: iOS
 - Browser Brave
 - Version 1.6.4

<img width="602" alt="wrong formatting" src="https://github.com/Clooos/Bubble-Card/assets/222462/75966a2a-abf7-4582-97d9-7240885d7405">

<img width="596" alt="correct formatting, optimised mode" src="https://github.com/Clooos/Bubble-Card/assets/222462/49d8c577-6a3e-4db5-bc9a-f2987555c4ef">

**Comment by Clooos** [comment]
This issue should be fixed now in the last beta, can you confirm this? :)

**Comment by wookash** [comment]
Hey, I’ve switched to another media card but before I deleted the one I’ve mentioned in this issue description was working fine a few days back so I think it’s all fixed now, unless someone else reports otherwise. Thanks!

**Comment by Clooos** [comment]
Great, thanks for the feedback!

**Comment by rairulyle** [comment]
Sorry to bump this issue @wookash @Clooos  It seems that it is still not fixed. Whenever the `upcoming-media-card` renders it is broken but when you open the popup via edit mode then view it, it will work.

I am suspecting that the js of it on init can't find the card due to popup not visible at the dom. 

Is there a way to load the js when the popup opens or a way to set in the popup to load it?

https://github.com/user-attachments/assets/9a46b6fb-213e-4945-a8dc-0759efaab237

**Comment by Clooos** [comment]
Hi again! Can you try this version to see if it works for you? You need to remove it from HACS first, then install it with the "Without HACS" method.

[bubble-card.js.zip](https://github.com/user-attachments/files/17668580/bubble-card.js.zip)

Once installed, clear your cache then check in the editor if you see v2.3.0-beta.5.

**Comment by rairulyle** [comment]
It still doesn't work. @Clooos 
![image](https://github.com/user-attachments/assets/c17b2d4e-016f-4bb0-867d-790890b647bd)

It might be something with on how I implemented popup? Also when you tested it have you tried doing a hard refresh and then opening it? That's where the bug happens, it works after edit but not when you exit edit mode and then refresh the page.

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#upcoming-tv"
    button_type: state
    entity: sensor.sonarr_upcoming_media_count
    name: Upcoming TV Shows
    icon: mdi:youtube-tv
    bg_color: var(--mdc-theme-surface)
    bg_opacity: "100"
    show_name: true
    show_state: true
    hide_backdrop: false
    show_attribute: true
    attribute: state_class
    background_update: false
    show_header: true
  - type: custom:upcoming-media-card
    entity: sensor.sonarr_upcoming_media
    image_style: fanart
    all_shadows: false
    hide_flagged: true
    card_mod:
      style: |
        .sona_fanart {
          background-position: center!important;
          background-size: cover!important;
          border-radius: 8px;
          margin: px!important;
        }
        .sona_fan_fanart {
          background: linear-gradient(to right, hsl(0deg 0% 0% / 50%) 48%, transparent 70%, #000 100%)!important;
          box-shadow: none!important;
        }

```

**Comment by Clooos** [comment]
That's what I tried indeed, I see that you use card mod, can you try again without it? I really want to be able to reproduce this issue.

**Comment by rairulyle** [comment]
@Clooos it still doesn't work even without it. I fully removed it, you can see the logs. Here's the video of it:

Uploading upcoming-media-card-popup-bug.mp4…

**Comment by Clooos** [comment]
I finally reproduced it! I can work on this issue now! 😃 

<img width="968" alt="image" src="https://github.com/user-attachments/assets/93989212-7b77-4f74-8f7f-901074c786b3">

**Comment by Clooos** [comment]
This should be fixed! Can you try it? The version number is still v2.3.0-beta.5.

[bubble-card.js.zip](https://github.com/user-attachments/files/17680525/bubble-card.js.zip)

**Comment by rairulyle** [comment]
@Clooos  that did it! Thank you very much! Now it's waiting for that version!

https://github.com/user-attachments/assets/c1c45a43-5ff9-4e79-ba33-34d72272076b

**Comment by Clooos** [comment]
Glad that's fixed! Thank you for all the details you provided!
