### ISSUE TITLE
Pop up card header (entity to display) does not update

### ISSUE THREAD

**Issue by alexanderlindstrom** [Clooos/Bubble-Card#372]
**Describe the bug**
Once the pop up card has loaded the header value never updates unless I reload page. 

**To Reproduce**
Add any entity to display to header in a pop up card
Change state of entity
Update is not reflected in header

**Expected behavior**
Value updated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: n/a
 - Browser Home Assistant Companion App
 - Version n/a

**Additional context**

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, I've just released a new version that that should fix that issue 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.0

**Comment by alexanderlindstrom** [comment]
Reopening this since it seem to persist after update...

**Comment by alexanderlindstrom** [comment]
Afraid not. Updated to latest, still same issue. See screenshot, arrow point to same sensor value, it's a temperature sensor. 
![Screenshot_20240220-092910~2](https://github.com/Clooos/Bubble-Card/assets/1754686/73b10d88-4d06-4076-806d-f4541dc0532a)

**Comment by Clooos** [comment]
Could you try to do the same with a light instead of a temperature sensor? Then open/close that light then tell me if it works that way, this is what I've did for my testing.

**Comment by alexanderlindstrom** [comment]
Yes. Works fine with light. Updates instantly.

**Comment by Clooos** [comment]
Thanks, I will take a closer look at this issue.

**Comment by alexanderlindstrom** [comment]
I wonder if it could be that a user input perhaps "forces" a state update frontend, but I have no base for that claim. 😅

**Comment by Clooos** [comment]
No, the state change even if you toggle that light with Google Home. But I'm on it.

**Comment by Clooos** [comment]
I've just tried with a temperature sensor and this working on my side. Have you changed anything related to the `recorder:` in your configuration.yaml?

**Comment by alexanderlindstrom** [comment]
I have not done anything witht he recorder in config. 

I am however not sure if this issue is constant or only under certain conditions. I will do some more testing on my own to see what conditions will make the header not update.

**Comment by Clooos** [comment]
Thanks, that would help me understanding what is happening here 🙂

**Comment by alexanderlindstrom** [comment]
I cannot reproduce it now, and every sensor update some to work fine. I have seen much improvement since the update. The screenshot was from this morning, so apperently it does happen from time to time, but perhaps it's just some edge case based on whatever. I think you shouldn't troubleshoot this any further. I will open a new issue if I notice some kind of pattern or if the issue gets more prevelent. Closing this as is.

**Comment by alexanderlindstrom** [comment]
Just as I posted that comment, I opened the app again (after about 5 minutes not having it open) and the sensor values werw out of sync. Maybe it could be an issue where the frontend does not have focus? Because the next update of the sensor value worked when I had the app open...

**Comment by Clooos** [comment]
Interesting, I might know what is happening here!

**Comment by Clooos** [comment]
Here is a test version that I really hope could fix this issue, just install it with the [Without HACS](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#without-hacs) installation method.

I can't wait to have your feedback on this!

[bubble-card.js.zip](https://github.com/Clooos/Bubble-Card/files/14344927/bubble-card.js.zip)

**Comment by Clooos** [comment]
This should be fixed now!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.2

**Comment by alexanderlindstrom** [comment]
I hate to open this again. But I noticed it still occurs, this time I navigated from energy dashbord and the values were out if sync.

So I had the dashboard with the bubble card loaded, switched to energy dashboard, didn't use the app for 10 minutes, opened the app and navigated back to dashboard with bubble card.

**Comment by Clooos** [comment]
Don't worry, I was not sure that it was perfectly fixed. But I should have found a new way to fix that 🤞

**Comment by alexanderlindstrom** [comment]
The more I think about it. The issue now seems to be exclusivly when I go to other parts of GUI then back to dashboard with bubble card. I hope that helps

**Comment by Clooos** [comment]
Hi, this issue should be finally fixed in the v2 beta! Can you confirm this?

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by sayam93** [comment]
works now!

**Comment by Clooos** [comment]
Yeah, finally! 😀

**Comment by alexanderlindstrom** [comment]
I can second that confirmation. Seem to work fine so far.

2.0 is a fantastic update overall 👍🏻

**Comment by phdalandan** [comment]
Hi everyone. Sorry to reopen this. I am quite new with everything about home lab. I just installed the Bubble card from HACS today (v2.4.0). I am having 2 issues. Both are in the header section.

First is the actual header information. I set the header to use the door sensor in my bedroom. The issue is it does not update the state. I included the luminance sensor right outside my door as a sub-button but it also does not update.

Second issue is that the close button (x) does not seem to be working. 

Did I miss any config here? Thank you!
