### ISSUE TITLE
issue with popup when using grid layout card

### ISSUE THREAD

**Issue by shift-del1** [Clooos/Bubble-Card#385]
**Describe the bug**
Not sure this is a bug or just the lack of my expertise, but I couldn't eliminate the below behavior. All 4 room cards are created identically, which means I have a grid layout within the popup, a default view for desktop (4 columns) and one for mobile (2 columns) and tablet (3 columns). Everything is controlled with mediaquery's min-width and max-width. Issue only present on the mobile dashboard and only for 2 of the cards. My first idea was the number of elements in the Lights and devices section (1 for non-working, 2 or more for working rooms), so I added a fake device to the non working room, but this didn't help. Second idea was the placement of the rooms (so any room in the first column (left) would fail), so I created a fifth room linking to the 4th room's popup, but it works fine. I also tried the column fix, but couldn't see any difference. Finally if I swap room 1 and room 2, the issue is also transferred to the second room, so somehow it is linked to the first column (left side, but the fifth card is also on the left and not affected).

**To Reproduce**
Honestly I can't even force my popups to behave the wrong way, it just happens in some of the cases.

**Expected behavior**
All room cards should be rendered the same way, so having 2 (or 3/4) columns.

**Screenshots**
[video](
https://github.com/Clooos/Bubble-Card/assets/63366470/accd5cdd-b421-49fd-bae9-fc51843a8aad)

**Desktop (please complete the following information):**
 - OS: / Windows 11 23H2
 - Browser: Chrome 121.0.2277.112
 - Version: 1.6.4

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - OS:  Android 14 QPR2
 - Browser: Home Assistant Companion App 2024.2.2-full / Chrome 121.0.6167.165
 - Version: 1.6.4

**Additional context**

Thank you! 🍻

**Comment by shift-del1** [comment]
Updated to 1.7.0, tried column_fix with different values (no luck), reverted everything to their original state I had in the afternoon when I created the issue, but now the rooms on the left hand side are OK and the ones on the right have an issue.

**Comment by Clooos** [comment]
This issue should be fixed in the v2 beta, can you confirm this?

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by shift-del1** [comment]
Installed v2.0.0-beta.6, but the issue is still there. The behavior is a bit different, but still not ok.

**Comment by Clooos** [comment]
Since v2 you need to put all your pop-ups **before** all your other cards on your view, this should definitely fix your issue. There is no need to use the column_fix anymore, I've removed it.

**Comment by shift-del1** [comment]
Sorry for not reading the instructions. You are right, moving the popups in front of the other cards solved the issue. The only modification I had to do is the activation of "Always hide the sidebar" switch, but otherwise it works as expected. Really nice job, thank you for your work and support. Really great addition to Home Assistant.

**Comment by Clooos** [comment]
I'm glad that this is finally fixed! 🎉
