### ISSUE TITLE
Still errors in latest beta

### ISSUE THREAD

**Issue by mfabiani53** [Clooos/Bubble-Card#445]
Still got same errors after installing latest beta

2024-04-14 09:51:22.763 ERROR (MainThread) [frontend.js.latest.202404042] Uncaught error from Chrome 123.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'state')
/local/bubble-card.js:1042:14975
/local/bubble-card.js:1042:14780
/local/bubble-card.js:1042:15081
K.updateBubbleCard (/local/bubble-card.js:1042:17444)
K.connectedCallback (/local/bubble-card.js:1042:124)
apply (src/scoped-custom-element-registry.js:248:41)
_addCardToColumn (src/panels/lovelace/views/hui-masonry-view.ts:257:15)
Promise.all (src/panels/lovelace/views/hui-masonry-view.ts:238:11)
2024-04-14 09:51:33.556 ERROR (MainThread) [frontend.js.latest.202404042] Uncaught error from Chrome 123.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'state')
/local/bubble-card.js:1042:14975
/local/bubble-card.js:1042:14780
/local/bubble-card.js:1042:15081
K.updateBubbleCard (/local/bubble-card.js:1042:17444)
K.connectedCallback (/local/bubble-card.js:1042:124)
apply (src/scoped-custom-element-registry.js:248:41)
_addCardToColumn (src/panels/lovelace/views/hui-masonry-view.ts:257:15)
Promise.all (src/panels/lovelace/views/hui-masonry-view.ts:238:11)
2024-04-14 09:51:53.099 ERROR (MainThread) [frontend.js.latest.202404042] Uncaught error from Chrome 123.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'state')
/local/bubble-card.js:1042:14975
/local/bubble-card.js:1042:14780
/local/bubble-card.js:1042:15081
K.updateBubbleCard (/local/bubble-card.js:1042:17444)
K.connectedCallback (/local/bubble-card.js:1042:124)
apply (src/scoped-custom-element-registry.js:248:41)
_addCardToColumn (src/panels/lovelace/views/hui-masonry-view.ts:257:15)
Promise.all (src/panels/lovelace/views/hui-masonry-view.ts:238:11)

**Comment by Clooos** [comment]
Hi and thank you for your feedback, just to be sure can you confirm that you are in v2.0.0 by looking in the editor, the version is shown at the bottom. I'm asking that because in some cases you need to clear your cache to really get the update.

**Comment by mfabiani53** [comment]
I just got the update and now it seems all ok... I will check it.

**Comment by mfabiani53** [comment]
Sorry, but the errrors are still there... i am forced to clear the caches every now and then....

![image](https://github.com/Clooos/Bubble-Card/assets/37701688/8e8bba25-44b5-4610-b232-1c0b5643076d)

**Comment by Clooos** [comment]
Can you tell me on what card you have this issue?

**Comment by mfabiani53** [comment]
Horizonta-button-stack

**Comment by Clooos** [comment]
I've released a new beta that should definitely fix that issue, here is the changelog:

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.2

**Comment by joshnewman17** [comment]
Unfortunately I'm still seeing this issue when using grid layout card. It seems to be dependent on the screen size. If I display the dashboard full screen on my desktop it displays properly, but on my tablet or if I shrink the window size down on the desktop the error returns. I have tried playing with the "width on desktop" option but so far no luck. The issue isn't present for me on version 1.7.3.

**Comment by Clooos** [comment]
I've worked a lot on this and I believe that this is fixed! I will release a new beta really soon.

**Comment by Clooos** [comment]
This issue is now fixed in the new beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3
