### ISSUE TITLE
Strange error in horizontal button card

### ISSUE THREAD

**Issue by krzysiek2788** [Clooos/Bubble-Card#452]
**Describe the bug**
On my Tablet dashboard there seams to be an issue with Horizontal Button card it isn't loading only showing error
![image](https://github.com/Clooos/Bubble-Card/assets/61471407/df6c318b-276c-4b1c-ae13-e4d77da40aff)
When enter edit mode error is still there
![image](https://github.com/Clooos/Bubble-Card/assets/61471407/14dc2aec-9402-4773-8bac-ca5ac2da8db6)

After I edit and do not change anything and save card is showing, but after full refresh again error is showed. Error showed on Tablet and Edge in Windows 10

**To Reproduce**
Don't know after update it happend. Tried to remove and recreate card but error is still there. In the other hand in my mobile dashboard all is working fine on Mobile phone and Desktop

**Expected behavior**
Show horizontal Button Card. After edit without changes and save:
![image](https://github.com/Clooos/Bubble-Card/assets/61471407/79ce3156-dfdd-4163-9076-668edcb9da60)

**Screenshots**
![image](https://github.com/Clooos/Bubble-Card/assets/61471407/794d63f5-57c7-415a-916b-14e5b9e03d39)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge 123.0.2420.81
 - Version 2.0.0 - beta-1

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 10
 - Browser Wallpanel app
 - Version 2.0.0 - beta-1

**Additional context**
Code is nothing sepcial no Styling look below
``type: custom:bubble-card
card_type: horizontal-buttons-stack
1_link: '#heating'
1_name: Ogrzewanie
1_icon: mdi:heat-wave
2_link: '#electricy'
2_name: Prąd
2_icon: mdi:transmission-tower
3_link: '#shopping'
3_name: Zakupy
3_icon: mdi:shopping-outline
4_link: '#media'
4_name: Rozrywka
4_icon: mdi:movie-open-settings
5_link: '#lights_house'
5_name: Dom
5_icon: mdi:ceiling-light-multiple-outline
5_entity: light.swiatla_w_domu
6_link: '#lights_backyard'
6_name: Podwórko
6_icon: mdi:dome-light
6_entity: light.swiatla_na_zewnatrz
7_link: '#state'
7_name: Stan domu
7_icon: mdi:home-assistant
8_link: '#cctv'
8_name: Monitoring
8_icon: mdi:cctv
width_desktop: 800px
is_sidebar_hidden: true
highlight_current_view: true
``

Thank you! 🍻

**Comment by joshnewman17** [comment]
I am experiencing this same issue.

**Comment by Clooos** [comment]
I know what is happening here, I will fix that for the next release.

**Comment by krzysiek2788** [comment]
> I've released a new beta that should definitely fix that issue, here is the changelog:
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.2

I'm afraid issue is still there. I have updated it and the error is still there. very strange issue. By other error type:
![image](https://github.com/Clooos/Bubble-Card/assets/61471407/e168a51f-e03b-4eda-88ff-6040e4774431)

**Comment by Clooos** [comment]
Damn, can you tell me what is the layout you are using for your dashboard?

**Comment by krzysiek2788** [comment]
It's Grid layout card

**Comment by Clooos** [comment]
Could you try this version with the [manual install method](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#without-hacs)? I really hope that this is fixed now 🤞

[bubble-card.js.zip](https://github.com/Clooos/Bubble-Card/files/15001481/bubble-card.js.zip)

**Comment by krzysiek2788** [comment]
I replaced file in installation folder and restarted browser but this error remains unchanged.

**Comment by Clooos** [comment]
You need to follow the steps I've sent, doing this is not working.

**Comment by dammic00** [comment]
I am experiencing the same problem, however I am encapsulating the horizontal bubble card in a decluttering template. If I create manually without the template, it does work.  see code below.
Template:
  footer_sticky_menu:
    card:
      type: custom:bubble-card
      card_type: horizontal-buttons-stack
      1_link: home1
      1_icon: mdi:home
      2_link: lights
      2_icon: mdi:lightbulb
      3_link: cameras
      3_icon: mdi:cctv
      4_link: '#thermo'
      4_icon: mdi:heat-wave
      5_link: '#FamilyRemote'
      5_icon: mdi:remote
      rise_animation: false
      6_link: '#garage'
      6_icon: mdi:garage
      7_icon: mdi:account-voice
      7_link: '#ann'
      8_icon: mdi:motion-sensor
      8_link: '#motion'
      is_sidebar_hidden: true

Card on dashboard:
type: custom:decluttering-card
template: footer_sticky_menu

**Comment by krzysiek2788** [comment]
> You need to follow the steps I've sent, doing this is not working. Just remove it from from HACS first.

Sorry for late response. I have done that but the issue is still the same, restarted HA and cleared browser cache
![image](https://github.com/Clooos/Bubble-Card/assets/61471407/842c9a28-470a-4f77-9056-9a9fdf737b6e)

**Comment by Clooos** [comment]
This issue is now fixed in the new beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3

**Comment by dammic00** [comment]
Thanks, Cloos, this has fixed my issue!

**Comment by Clooos** [comment]
Yeah, I was not sure! Thanks for the feedback!

**Comment by krzysiek2788** [comment]
Maybe that solved dammic00 issue but mine stays like it was 🤣 nothing changes.

**Comment by Clooos** [comment]
Are you sure that you are on the last beta, you can see that in the editor.

**Comment by krzysiek2788** [comment]
> Are you sure that you are on the last beta, you can see that in the editor.

Yes it is the latest version even restart didn't change anything.

**Comment by dammic00** [comment]
Noticed that the dashboard tab view-type cannot be set to sideview or sections view, masonry or vertical do not exhibit the error.

**Comment by Clooos** [comment]
Thanks for the info! I will take a look at this tomorrow.

**Comment by joshnewman17** [comment]
I am still experiencing the same issue on the latest beta. Thanks for all the hard work! My new mobile dashboard is coming along great but the tablets that use grid view are having trouble.

**Comment by Clooos** [comment]
This issue should be fixed now, I'm waiting for your feedback 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.6

**Comment by krzysiek2788** [comment]
That is true the issue is finally solved. Many thanks

**Comment by Clooos** [comment]
Finally! 😀
