### ISSUE TITLE
HSB doesn’t render on refresh

### ISSUE THREAD

**Issue by FrenchieKing757** [Clooos/Bubble-Card#464]
**Describe the bug**
HSB card does not render when dashboard is opened. When editing dashboard and entering the edit dialog for the HSB card, it does render properly, as soon as refresh is done, it produces error. 

**To Reproduce**
1. Go to dashboard. See error. 
2. Click on top right “three dots”, edit dashboard board, select “edit” on HSB card group and renders as expected. 
3. Click “save” then click “done”. Card renders as expected on main dashboard. 
4. Refresh dashboard. See error

**Expected behavior**
HSB rendering on startup and refresh. 

**Screenshots**
![IMG_1181](https://github.com/Clooos/Bubble-Card/assets/92132559/08b37d21-e9ab-4c44-b14a-86b8aaeab8dd)
![IMG_1182](https://github.com/Clooos/Bubble-Card/assets/92132559/df128ab1-d10d-46fa-af64-79bf939061da)
![IMG_1183](https://github.com/Clooos/Bubble-Card/assets/92132559/d15c9999-83ec-45c6-a132-1ef4f3767394)
![IMG_1184](https://github.com/Clooos/Bubble-Card/assets/92132559/dea30199-7aac-48d5-bb86-17ba5fb33d29)

**Informations (please complete the following information):**
 - OS: iOS 17.4.1
 - HA Companion App 
 - Bubble Card version 2.0.0 beta 2 (says beta 1 in the UI, but I’ve ensured I downloaded beta 2)
 - Home Assistant version 2024.4.3

**Comment by Clooos** [comment]
I'm aware of this issue and it is already fixed on my side, just wait for the next beta :)

**Comment by FrenchieKing757** [comment]
> I'm aware of this issue and it is already fixed on my side, just wait for the next beta :)

Thank you and I love the card.

**Comment by Clooos** [comment]
This issue is now fixed in the new beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3

**Comment by FrenchieKing757** [comment]
> This issue is now fixed in the new beta!
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3

Hey Clooos, thanks for the update. I’m still getting the JS error for the HSB. I removed the bubble fix from my config.yaml and restarted. Not sure if you have another recommendation.

**Comment by Clooos** [comment]
Can you send me the exact error you have?

And also are you sure that the version number is the last one? You can see it in the editor, there is sometime cache issues.

**Comment by FrenchieKing757** [comment]
> Can you send me the exact error you have?
> 
> And also are you sure that the version number is the last one? You can see it in the editor, there is sometime cache issues.

Sure thing. 
![IMG_1246](https://github.com/Clooos/Bubble-Card/assets/92132559/6f2f8559-6c40-4fba-a715-35c08f9f9341)
![IMG_1247](https://github.com/Clooos/Bubble-Card/assets/92132559/a510b51d-21aa-41f4-a0a3-0afe3e1cad0b)

**Comment by Clooos** [comment]
This issue should be fixed now, I'm waiting for your feedback 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.6

**Comment by FrenchieKing757** [comment]
> This issue should be fixed now, I'm waiting for your feedback 🤞
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.6

BOOM! You got it. No issues on refresh either. Thank you so much.

**Comment by Clooos** [comment]
Yeah finally! 🎉
