### ISSUE TITLE
Multiple popups auto-close bug

### ISSUE THREAD

**Issue by bambucha3** [Clooos/Bubble-Card#685]
When you have multiple popups on the same dashboard, when you click through them - opening one after another, they auto close faster than expected.
Its probably an issue with the popup timer not restarting after opening a new popup.

**To Reproduce**  
1. Create a new dashboard with 2 popups.
2. Set auto close to 60 seconds.
3. Open first popup. Wait 30 sec. Open 2nd popup.
4. 2nd popup will close after 30 sec, not after 60 sec.

Steps to reproduce the behavior - another case:
1. Create a new dashboard with 4 popups.
2. Set auto close to 60 seconds.
3. Click through popups, one after another.
4. After a few opens, popups will start to close immediately after opening.

**Expected behavior**  
2nd popup should close after the time specified in the popup runs out.
Popups should stay open for the specified amount of time.

Thank you! 🍻

**Comment by bambucha3** [comment]
This issue still persists on the 2.2 beta 3.
Also a new repo case:
- Tapping the same navigation bar button multiple times one after another, sometimes shows only the blurred background, but not the popup. Auto close is set to 60s.

I think the issue is that each popup open triggers a new timer, and does not clear the old ones. This means if you open multiple popups in quick succession, you have multiple timers running, closing the currently opened popup after they finish.
When popup gets closed, it should clear the timer it created, since it does not need it anymore.

**Comment by Clooos** [comment]
Hi and thank you for the feedback! This issue should be fixed in the next release 🤞

**Comment by Clooos** [comment]
This issue should be fixed now 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.0

**Comment by bambucha3** [comment]
Hey,
I just updated, but the issue persists.
I think that you fixed the case where you close the popup by pressing the X button.
But if you close the popup by opening another one (clicking nav buttons one after another), the issue still persists.
I could reproduce it also on my PC, just make a 3 navbar buttons, 3 popups and click the buttons one after another.

**Comment by Clooos** [comment]
Damn 😅 I will try again for the next release! Thank you for the fast feedback!

**Comment by Clooos** [comment]
I've tried and this one is the one!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.2

**Comment by Clooos** [comment]
@bambucha3 Is it working for you this time? I'm unable to reproduce this issue anymore.

**Comment by bambucha3** [comment]
Hey
I tested on PC and mobile, seems like its working!
Could not reproduce.
