### ISSUE TITLE
Slider cards slide action triggers sub-card select

### ISSUE THREAD

**Issue by alex-phillips** [Clooos/Bubble-Card#710]
**Describe the bug**  
If you have a slider button with a sub-button that is a select, sliding the button (volume, light, etc), if you slide and stop over the select button, it triggers / opens the select button.

**To Reproduce**  
1. Create a slider button
2. Add a sub button that is a select
3. Slide the value to where the cursor is on top of the select button and let go

**Expected behavior**  
The slider value should change, but the select button should not trigger / open

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, this issue is fixed in the v2.2.1, have you tried it? If yes have you cleared you browser/app cache?

**Comment by alex-phillips** [comment]
I did and it still persists. I think this is opposite of the original issue I posted (which was a duplicate). In the original issue, clicking on the select triggered the slider. But in this case, sliding the slider over the select triggers the select box.

The original issue I mentioned above is fixed.

**Comment by Clooos** [comment]
What browser do you use? Because I'm unable to reproduce this issue.

**Comment by alex-phillips** [comment]
Firefox 128.0.2
