### ISSUE TITLE
laggy pop ups when using multiple mini-graph-cards

### ISSUE THREAD

**Issue by Dschiii** [Clooos/Bubble-Card#724]
hello,

after the recent updates of bubble cards I noticed drastic performance improvements on my Pixel 8 (on my PC everything was smooth all the time) so I wanted to convert my dashboard completely to pop-up cards instead of using sub views for my rooms.
since I also decided to use the sections layout I figured the cleanest way to do things is to simply copy each element from my sub views to the corresponding pop-up cards.

after completing the "migration" of each room, I gave it another try to see if things are still running smoothly.
they did, until I decided to use mini-graph-cards, two for each room, one showing the temperature history (24h) and one for humidity (24h).
I used a grid (2 cols, 1 row) to show these graphs side by side for 4 rooms, so I had a total of 8 min-graph-cards hidden in the pop-ups within my main dashboard.

it seems like pulling all this data in a single dashboard view is too much load to still have a smooth pop-up animation.
after removing all the mini-graph-cards everything went back to being perfectly smooth.

I know this isn't a performance issue of bubble-cards itself, but unfortunately it shows when using pop-ups (on a decent device) and I thought you might want to know and give it a try yourself.

here's the config of one of my mini-graph-cards:

type: custom:mini-graph-card
entities:
  - sensor.aquara_hygrometer1_humidity
name: Luftfeuchtigkeit
align_state: center
align_icon: right
line_width: 10
font_size: 100
icon: mdi:water-percent
show:
  extrema: false
  points: false
  icon: true
  name: true
  state: true
  labels: false
  fill: true
  icon_adaptive_color: true
color_thresholds:
  - value: 0
    color: '#ff6a00'
  - value: 45
    color: '#1aff00'
  - value: 60
    color: '#1c9fd4'
animate: true
hour24: true

Cheers!

**Comment by Clooos** [comment]
Hi and thank you for the feedback! This is interesting because the pop-ups are acting like the conditional cards, this means that the content of the pop-ups is removed when they are closed and re-created when they are opened. So even if you had 100 pop-ups this should not slow down your dashboard, or just a bit.

But indeed, some heavier cards can slow down a pop-up opening, is your issue just with the animations?

**Comment by Dschiii** [comment]
thanks for the heads-up, sounds like this shouldn't be an issue then.
I could reproduce the behaviour on three devices (Pixel 8, Pixel 6, Pixel 6a) so it's either my dashboard setup or something with my HA instance.

and yes, it's just the pop-up animation (sliding up from the bottom with default settings) that's laggy, sometimes it doesn't even slide but just instantly shows after about a second delay.
there are no issues with any functions at all.

**Comment by Clooos** [comment]
I will work on that, there is probably something that I can do to ensure that the animation is always working.

On my side I've already worked on the closing animation that was not always shown as well.

**Comment by Clooos** [comment]
Hi, I've just released the v2.2.3, can you tell me if it's better?

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.3

**Comment by Dschiii** [comment]
hi,

I just updated to 2.2.3 and added the mini graph cards back to my room popups.
for 3 of 4 rooms it looks way smoother now, though still not as smooth as without them.
I tried playing around with the "animate" and colorthreshold parameters of mini-graph-card but this doesn't seem to make any difference.
I also found that it gets better when I re-open the pop-ups multiple times.

here's a screen recording from my pixel 8 (app cache cleared shortly before) for the one room (my office "Büro") where you can clearly see the first popup lagging the first time it opens up
https://drive.google.com/file/d/1e7EGl1uIWAqGMxxI1RRX59goitXJj8n0/view?usp=drive_link

note: I have 3 nested conditions in there as well so that might also be not ideal in terms of performance.

btw: I highly appreciate your quick responses and fixes but I seem to be the only person having this issue so please don't treat this as high-prio! :)

**Comment by Dschiii** [comment]
update: 
the behaviour was quite odd for this one room so I wanted to compare every detail of the popups as well as the button (mushroom template card) triggering the pop up.
I found absolutely no differences in the buttons for each room, though using the "Büro" button felt delayed in comparison - even after removing everything from the popup card.

after creating a new mushroom template card - which I configured excatly the same way as the laggy one - the popup now triggers immeadiately!
it seems like something was wrong with this button, no idea what or how I broke it.

mini-graph-cards still seem to make my popups just a tiny bit slower/sometimes laggy - regardless of how many I add (2 or 8 doesn't matter).
this goes especially for the first time triggering the popup after opening the app on my pixel 8.
pop-ups not containing any mini-graph-cards are skipping the first animation completely after restarting the companion app. after that everthing works smoothly as expected.

this is just a minor inconvenience rather than an issue to be honest.

**Comment by Clooos** [comment]
Hi again and thank you for the details, I've just released a new version, have you tried it?

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.4

**Comment by Dschiii** [comment]
hi, 
i just updated and cleared the cache.
looks way smoother now when adding the mini graph cards :)
thanks for the updates!

**Comment by Clooos** [comment]
Great! Would you say that this issue is fixed or there is still a big difference when the mini graphs cards are added?

**Comment by Dschiii** [comment]
from what I can tell there is no difference anymore so I'd das it's fixed :)

thanks for your great work!

**Comment by Clooos** [comment]
Wow I was not expecting that, glad that it's fixed!
