### ISSUE TITLE
Dragging over a bubble card triggers a popup

### ISSUE THREAD

**Issue by michaelarnauts** [Clooos/Bubble-Card#839]
**Describe the bug**  
When dragging over a button card (to scroll down), a popup is triggered.

Also, when using swipe navigation, the same happens when scrolling left/right to navigate to a different tab.

**To Reproduce**  
1. Add a few bubble cards to a dashboard 
2. Drag down to scroll (on mobile)
3. A popup is triggered of the bubble card where dragging was initiated.

**Expected behavior**  
Just scroll down without triggering a popup.

**Screenshots**  

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Your code here
```

**Informations (please complete the following information):**  
 - OS: Android
 - Browser/App: Official HA app
 - Bubble Card version: 2.3.0 beta 2
 - Home Assistant version: 2024.10.1

**Additional context**  

Thank you! 🍻

**Comment by FalkPe** [comment]
I have the same problem

**Comment by Tee86** [comment]
@Clooos , not sure if this info helps you, but I don't have this issue at all and the config is the same:
OS: Android
Browser/App: Official HA app
Bubble Card version: 2.3.0 beta 2
Home Assistant version: 2024.10.1

Nor my client who uses iOs app reported this behaviour.
Looks like a specific conflict issue with other integration that I don't have installed on my server.

**Comment by Clooos** [comment]
This issue is already fixed, I just need a bit more time for releasing the new beta.

**Comment by michaelarnauts** [comment]
@Clooos could you already commit the fix to the main branch? I could use the latest main in HACS then while waiting for a release.

**Comment by Clooos** [comment]
Done 👌

**Comment by michaelarnauts** [comment]
Unfortunately, it still has an issue, when scrolling down, but the viewport is already at the bottom (or scrolling up at the top), the click is still triggered.

A click is also triggered when scrolling to the side (when using swipe navigation to switch to the next tab).

**Comment by peterthepeter** [comment]
Hello,

Unfortunately I still have the problem with Bubble Card v2.3.0-beta.3

on my iPhone with Safari or Arc.
iOS 18.0.1



Best regards
Christian

**Comment by sebster6** [comment]
Same issue on beta 4 as well :(

**Comment by Clooos** [comment]
Hi! This issue should be definitely fixed in the next release, I've added a new system that disable all actions when a scroll is detected. This time it should perfect 🤞

**Comment by michaelarnauts** [comment]
> Hi! This issue should be definitely fixed in the next release, I've added a new system that disable all actions when a scroll is detected. This time it should perfect 🤞

There still is the case where you drag down while at the bottom of the page. This doesn't trigger a scroll, but shouldn't trigger a click. 

The same for horizontal dragging (when used with swipe navigation), this also doesn't scroll.

**Comment by michaelarnauts** [comment]
@Clooos beta5 fixed it for the vertical scrolling, but it still triggers a popup (or a click when the action is toggle) when doing a horizontal swipe (to move to the next page).

**Comment by Clooos** [comment]
Damn, I haven't covered the horizontal swipe indeed! 🫠

**Comment by michaelarnauts** [comment]
I have swipe navigation installed (https://github.com/zanna-37/hass-swipe-navigation) and configured.

Then, when you have multiple tabs in your dashboard, you can swipe left and right to move to another tab.

When doing this over a bubble cart button, the more info dialog pops up. It actually seems to trigger the click action causing the more info dialog to show.

**Comment by Clooos** [comment]
Do you had this issue before the v2.3.0 betas? Even if it was not the case before, I have developed a new system for the actions that is much more efficient and I'm not sure that I can do much since this issue seems to only happen in combination with swipe navigation.

But I'm probably wrong, it is just difficult for me to cover every cases just by myself, so if anyone want to contribute on this, he will be more than welcome!

**Comment by jasjeetsuri** [comment]
I don’t have HASS Swipe installed.
When I swipe from the left on the HA mobile App to open the sidebar, the bubble card toggles where I swiped. This causes random stuff to turn on :(

**Comment by Clooos** [comment]
Hi! After some more investigation, I should have finally fixed this issue! 🤞

This fix will be available in the next beta.

**Comment by peterthepeter** [comment]
It's fixed for me

**Comment by edrude** [comment]
Vertical scrolling issue fixed for me moving to v3 rc. 

iOS 18.5
