### ISSUE TITLE
Clicking outside of popup onto custom:grid-layout does not dismiss popup

### ISSUE THREAD

**Issue by TinyShark** [Clooos/Bubble-Card#88]
My Dashboards are created with css grid using layout-card (https://github.com/thomasloven/lovelace-layout-card).

When using bubble-card popups, I cannot dismiss the popup when clicking outside of it. This is only the case where a css grid is defined. If I click outside of all grid areas, the popup will dismiss was expected.

 </br></br>

<img width="1384" alt="Screenshot 2023-10-02 at 10 32 37" src="https://github.com/Clooos/Bubble-Card/assets/23080224/928ee81c-2e0e-402c-9d4f-c1ccb9034446">

 
 
 </br></br></br>
Test Dashboard to simplify/explain what the issue is:

```
title: Test Pop
path: testpop
panel: false
icon: mdi:lamp
badges: []
type: custom:grid-layout
layout:
  grid-template-columns: 1fr 200px 200px 1fr
  grid-template-rows: 100px 100px 100px

cards:
  - type: vertical-stack
    cards:
      - type: custom:bubble-card
        card_type: pop-up
        hash: "#testpop"
      - type: button
        entity: sun.sun
  - type: custom:bubble-card
    card_type: horizontal-buttons-stack
    1_name: testpop
    1_icon: mdi:account
    1_link: "#testpop"
    1_entity: sun.sun

```

**Comment by oyvhov** [comment]
I have the same problem. Also, the X button does also not work when using css grid

**Comment by Clooos** [comment]
Hi and thanks for your feedback, can you tell me if it's fixed in the v1.0.1?
https://github.com/Clooos/Bubble-Card/releases/tag/v1.0.1

**Comment by TinyShark** [comment]
Hi Clooos - thanks for looking at this! Unfortunately the problem persists in v1.0.1. I have also found two further issues that I will open now.

![ezgif com-video-to-gif](https://github.com/Clooos/Bubble-Card/assets/23080224/1b64b3c6-4245-4a04-b374-8ff5f1f4256c)

**Comment by Clooos** [comment]
I will have to install layout-card to try this, I hope that this is something that I can fix.

**Comment by TinyShark** [comment]
FIXED with versions > 1.7.0

Thanks Cloos!
